<a href="https://colab.research.google.com/github/lewisgregory5-collab/python-projects/blob/main/Another_copy_of_CO4_Hello_world_in_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from datetime import datetime

# Example data structure (you could also load from CSV or Excel)
data = {
    "Item": [
        "car battery","groceries","tissue","lawn equipment","boost drink",
        "oil change","wired mouse","gasoline","lottery","rock salt"
    ],
    "Total Cost":[311.01,567.76,22.25,438.82,640.77,102.17,14.07,113.15,921.30,85.00],
    "Purchase Date":[
        "2026-02-03","2026-03-28","2025-08-23","2025-09-04","2025-11-13",
        "2026-02-26","2026-02-22","2026-01-14","2024-11-25","2025-11-25"
    ],
    "Target Daily Cost":[3.25,15.00,0.06,1.75,3.75,1.65,0.20,1.00,1.50,0.50]
}

df = pd.DataFrame(data)

# Convert purchase date
df["Purchase Date"] = pd.to_datetime(df["Purchase Date"])

# Today's date
today = pd.Timestamp.today().normalize()

# Days since purchase
df["Days Since Purchase"] = (today - df["Purchase Date"]).dt.days

# Cost per day
df["Cost Per Day"] = df["Total Cost"] / df["Days Since Purchase"]

# Break-even days
df["Break-even Days"] = df["Total Cost"] / df["Target Daily Cost"]

# Break-even date
df["Break-even Date"] = df["Purchase Date"] + pd.to_timedelta(df["Break-even Days"], unit="D")

# Remaining days
df["Remaining Days"] = (df["Break-even Date"] - today).dt.days

# Percent completed
df["Percent Completed"] = (df["Days Since Purchase"] / df["Break-even Days"]) * 100

# Monthly equivalent
df["Per Month"] = df["Cost Per Day"] * 30

# Round values
df = df.round({
    "Cost Per Day":2,
    "Break-even Days":2,
    "Percent Completed":2,
    "Per Month":2
})

print(df)

             Item  Total Cost Purchase Date  Target Daily Cost  \
0     car battery      311.01    2026-02-03               3.25   
1       groceries      567.76    2026-03-28              15.00   
2          tissue       22.25    2025-08-23               0.06   
3  lawn equipment      438.82    2025-09-04               1.75   
4     boost drink      640.77    2025-11-13               3.75   
5      oil change      102.17    2026-02-26               1.65   
6     wired mouse       14.07    2026-02-22               0.20   
7        gasoline      113.15    2026-01-14               1.00   
8         lottery      921.30    2024-11-25               1.50   
9       rock salt       85.00    2025-11-25               0.50   

   Days Since Purchase  Cost Per Day  Break-even Days  \
0                   81          3.84            95.70   
1                   28         20.28            37.85   
2                  245          0.09           370.83   
3                  233          1.88         

In [ ]:
import pandas as pd

# Monthly income (budget)
monthly_income = 3710.76

data = [
("CONSUMERS E",284.29),
("XFINITY",123.37),
("VERIZON",101.28),
("AUTO INS",421.00),
("NETFLIX",26.99),
("YOUTUBE",15.99),
("ADT 1",85.97),
("APPLE 1",3.17),
("ADT 2",25.29),
("DTE",200.00),
("GROCERY",495.05),
("APPLE 2",1.99),
("H&R BLOCK",0.00),
("GOOGLE 1",3.99),
("GASOLINE",113.15),
("SUMMER TAX",164.52),
("HOME INS",144.83),
("CASH",0.00),
("WINTER TAX",24.51),
("MICROSOFT",8.83),
("APPLE 3",0.99),
("AUTO DEPRECIATION",0.00),
("LOAN",0.00),
("HAIRCUT",18.08),
("LOTTERY",55.16),
("GOOGLE 2",13.99),
("OIL CHANGE",62.16),
("WATER BILL",49.09),
("NEW BATTERY",129.60),
("FEDERAL TAX",250.25),
("YARD TOOLS",59.33),
("DINING OUT",9.81)
]

df = pd.DataFrame(data, columns=["Category","Monthly Cost"])

# percent of income
df["Percent"] = (df["Monthly Cost"] / monthly_income) * 100

# daily cost
df["Daily Cost"] = df["Monthly Cost"] / 30.44

# reorder columns
df = df[["Percent","Category","Monthly Cost","Daily Cost"]]

total_spent = df["Monthly Cost"].sum()
remaining = monthly_income - total_spent
remaining_percent = (remaining / monthly_income) * 100

print(df.round(2))
print("\nBudget:", round(monthly_income,2))
print("Spent:", round(total_spent,2))
print("Remaining:", round(remaining,2))
print("Remaining %:", round(remaining_percent,2),"%")

    Percent           Category  Monthly Cost  Daily Cost
0      7.66        CONSUMERS E        284.29        9.34
1      3.32            XFINITY        123.37        4.05
2      2.73            VERIZON        101.28        3.33
3     11.35           AUTO INS        421.00       13.83
4      0.73            NETFLIX         26.99        0.89
5      0.43            YOUTUBE         15.99        0.53
6      2.32              ADT 1         85.97        2.82
7      0.09            APPLE 1          3.17        0.10
8      0.68              ADT 2         25.29        0.83
9      5.39                DTE        200.00        6.57
10    13.34            GROCERY        495.05       16.26
11     0.05            APPLE 2          1.99        0.07
12     0.00          H&R BLOCK          0.00        0.00
13     0.11           GOOGLE 1          3.99        0.13
14     3.05           GASOLINE        113.15        3.72
15     4.43         SUMMER TAX        164.52        5.40
16     3.90           HOME INS 

In [ ]:
# keep

import pandas as pd
from datetime import datetime, timedelta

items = []

today = datetime.today()

print("\nExpense Break-Even Calculator\n")

while True:

    name = input("Enter item name (or type 'done'): ")

    if name.lower() == "done":
        break

    total_cost = float(input("Total cost: $"))
    purchase_date = input("Purchase date (YYYY-MM-DD): ")
    target_daily_cost = float(input("Target daily cost: $"))

    purchase_date = datetime.strptime(purchase_date, "%Y-%m-%d")

    days_since_purchase = (today - purchase_date).days
    cost_per_day = total_cost / days_since_purchase
    break_even_days = total_cost / target_daily_cost
    break_even_date = purchase_date + timedelta(days=break_even_days)
    remaining_days = (break_even_date - today).days
    per_month = cost_per_day * 30
    completion_rate = (days_since_purchase / break_even_days) * 100

    items.append([
        name,
        total_cost,
        purchase_date.date(),
        days_since_purchase,
        round(cost_per_day,2),
        target_daily_cost,
        round(break_even_days,2),
        break_even_date.date(),
        remaining_days,
        round(per_month,2),
        round(completion_rate,2)
    ])

df = pd.DataFrame(items, columns=[
    "Item",
    "Total Cost",
    "Purchase Date",
    "Days Since Purchase",
    "Cost Per Day",
    "Target Daily Cost",
    "Break-even Days",
    "Break-even Date",
    "Remaining Days",
    "Per Month",
    "Completion Rate %"
])

print("\nResults:\n")
print(df)

df.to_excel("expense_tracker_output.xlsx", index=False)

print("\nSaved to: expense_tracker_output.xlsx")





Expense Break-Even Calculator

Enter item name (or type 'done'): car battery
Total cost: $311.01
Purchase date (YYYY-MM-DD): 2026-02-03
Target daily cost: $3.25
Enter item name (or type 'done'): groceries
Total cost: $4119.15
Purchase date (YYYY-MM-DD): 2025-04-27
Target daily cost: $11
Enter item name (or type 'done'): tissue
Total cost: $22.25
Purchase date (YYYY-MM-DD): 2025-08-23
Target daily cost: $.06
Enter item name (or type 'done'): done

Results:

          Item  Total Cost Purchase Date  Days Since Purchase  Cost Per Day  \
0  car battery      311.01    2026-02-03                   84          3.70   
1    groceries     4119.15    2025-04-27                  366         11.25   
2       tissue       22.25    2025-08-23                  248          0.09   

   Target Daily Cost  Break-even Days Break-even Date  Remaining Days  \
0               3.25            95.70      2026-05-09              11   
1              11.00           374.47      2026-05-06               7   
2 

In [ ]:

# keep this one
import pandas as pd
from datetime import datetime, timedelta

items = []

while True:

    item = input("\nEnter item name (or type 'done' to finish): ")

    if item.lower() == "done":
        break

    try:
        total_cost = float(input("Total cost ($): "))
        target_daily_cost = float(input("Target daily cost ($): "))
        purchase_date = input("Purchase date (YYYY-MM-DD): ")

        purchase_date = datetime.strptime(purchase_date, "%Y-%m-%d")
        today = datetime.today()

        days_since = (today - purchase_date).days

        cost_per_day = total_cost / days_since if days_since > 0 else total_cost

        break_even_days = total_cost / target_daily_cost

        break_even_date = purchase_date + timedelta(days=break_even_days)

        remaining_days = (break_even_date - today).days

        per_month = cost_per_day * 30.42

        items.append({
            "Item": item,
            "Total Cost": total_cost,
            "Days Since Purchase": days_since,
            "Cost Per Day": round(cost_per_day,2),
            "Target Daily Cost": target_daily_cost,
            "Break-even Days": round(break_even_days,2),
            "Break-even Date": break_even_date.date(),
            "Remaining Days": remaining_days,
            "Per Month": round(per_month,2)
        })

    except ValueError:
        print("Invalid entry. Try again.")

df = pd.DataFrame(items)

print("\nCost Tracker Table\n")
print(df)

# Save to Excel
df.to_excel("cost_tracker.xlsx", index=False)

print("\nFile saved as cost_tracker.xlsx")


Enter item name (or type 'done' to finish): coffe
Total cost ($): 8.99
Target daily cost ($): 1.26
Purchase date (YYYY-MM-DD): 2026-02-18

Enter item name (or type 'done' to finish): done

Cost Tracker Table

    Item  Total Cost  Days Since Purchase  Cost Per Day  Target Daily Cost  \
0  coffe        8.99                   66          0.14               1.26   

   Break-even Days Break-even Date  Remaining Days  Per Month  
0             7.13      2026-02-25             -60       4.14  

File saved as cost_tracker.xlsx


In [ ]:
import pandas as pd
from datetime import datetime, timedelta

# Data
data = {
    "Category": ["2025-Taxes", "H&R Block fee", "2023-Taxes", "H&R Block fee"],
    "Total Cost": [2768.00, 237.00, 6871.69, 120.25],
    "Start Date": [
        "2026-04-14",
        "2026-04-14",
        "2026-02-24",
        "2026-02-24"
    ],
    "Target Daily Cost": [5, 3, 9, 1]
}

df = pd.DataFrame(data)

# Convert dates
df["Start Date"] = pd.to_datetime(df["Start Date"])
today = pd.Timestamp.today().normalize()

# Days tracked
df["Days Tracked"] = (today - df["Start Date"]).dt.days

# Cost per day
df["Cost Per Day"] = df["Total Cost"] / df["Days Tracked"]

# Break-even days
df["Break-even Days"] = df["Total Cost"] / df["Target Daily Cost"]

# Break-even date
df["Break-even Date"] = df["Start Date"] + pd.to_timedelta(df["Break-even Days"], unit="D")

# Percent of target
df["% of Target"] = (df["Cost Per Day"] / df["Target Daily Cost"]) * 100

print(df)

        Category  Total Cost Start Date  Target Daily Cost  Days Tracked  \
0     2025-Taxes     2768.00 2026-04-14                  5            11   
1  H&R Block fee      237.00 2026-04-14                  3            11   
2     2023-Taxes     6871.69 2026-02-24                  9            60   
3  H&R Block fee      120.25 2026-02-24                  1            60   

   Cost Per Day  Break-even Days               Break-even Date  % of Target  
0    251.636364       553.600000 2027-10-19 14:24:00.000000000  5032.727273  
1     21.545455        79.000000 2026-07-02 00:00:00.000000000   718.181818  
2    114.528167       763.521111 2028-03-28 12:30:23.999999999  1272.535185  
3      2.004167       120.250000 2026-06-24 06:00:00.000000000   200.416667  


In [ ]:
import pandas as pd

# Data extracted from cell SkOwT4t7-VPf, structured to match relevant columns
data = [
    ["Car battery", 311.01, "2/3/2026", 70, 4.44, 1.00, 311.01, "12/11/2026", 241.01, 135.16, "This is not paid for", 3.64],
    ["Groceries", 266.35, "3/27/2026", 18, 14.80, 1.00, 266.35, "12/18/2026", 248.35, 450.13, "This is not paid for", 12.13],
    ["Tissue", 22.25, "8/23/2025", 234, 0.10, 1.00, 22.25, "9/14/2025", -211.75, 2.89, "This is paid for", 0.08],
    ["Yard equipment", 438.82, "9/4/2025", 222, 1.98, 1.00, 438.82, "11/16/2026", 216.82, 60.13, "This is not paid for", 1.62],
    ["Boost drink", 640.77, "11/13/2025", 152, 4.22, 1.00, 640.77, "8/15/2027", 488.77, 128.24, "This is not paid for", 3.46],
    ["Oil change", 102.17, "2/26/2026", 47, 2.17, 1.00, 102.17, "6/8/2026", 55.17, 66.13, "This is not paid for", 1.78],
    ["Wired mouse", 14.07, "2/22/2026", 51, 0.28, 1.00, 14.07, "3/8/2026", -36.93, 8.39, "This is paid for", 0.23],
    ["Gasoline", 113.15, "1/14/2026", 90, 1.26, 1.00, 113.15, "5/7/2026", 23.15, 38.24, "This is not paid for", 1.03],
    ["Lottery", 921.30, "11/25/2024", 505, 1.82, 1.00, 921.30, "6/4/2027", 416.30, 55.50, "This is not paid for", 1.50],
    ["Rock salt", 85.00, "11/25/2025", 140, 0.61, 1.00, 85.00, "2/18/2026", -55.00, 18.47, "This is paid for", 0.50],
    ["Razor", 32.63, "11/21/2025", 144, 0.23, 1.00, 32.63, "12/23/2025", -111.37, 6.89, "This is paid for", 0.19],
    ["Tissue, paper towel", 41.48, "12/7/2025", 128, 0.32, 1.00, 41.48, "1/17/2026", -87.00, 9.86, "This is paid for", 0.27],
    ["Hair cut", 85.00, "11/25/2025", 140, 0.61, 1.00, 85.00, "2/18/2026", -55.00, 18.47, "This is paid for", 0.50],
    ["New tires", 847.88, "9/19/2025", 207, 4.10, 1.00, 847.88, "1/14/2028", 641.00, 124.60, "This is not paid for", None],
]

columns = [
    "Item", "Total Cost", "Purchase Date", "Days Since Purchase",
    "Cost Per Day", "Target Daily Cost", "Break-even Days",
    "Break-even Date", "Remaining Days", "Per Month",
    "Status", "% Monthly Income"
]

df_from_text = pd.DataFrame(data, columns=columns)

# Convert date columns to datetime objects
df_from_text["Purchase Date"] = pd.to_datetime(df_from_text["Purchase Date"], format="%m/%d/%Y")
df_from_text["Break-even Date"] = pd.to_datetime(df_from_text["Break-even Date"], format="%m/%d/%Y")


## Original Data from cell `SkOwT4t7-VPf` (now converted to DataFrame)
```
Item	Total Cost	Purchase Date	Today	Days Since Purchase	Cost Per Day	Target Daily Cost	Break-even Days	Break-even Date	Remaining days		Per month				Target	Item			Spending increase		% of Monthly income
Car battery	$311.01	2/3/2026	Tuesday,April 14,2026	70	$4.44 	$1.00	311.01	Friday,December 11,2026	241.01 	Tuesday,April 14,2026	$135.16 				22.51%	New battery	This is not paid for		100.00%		3.64%			variable cost	$998.50
Groceries	$266.35 	3/27/2026	Tuesday,April 14,2026	18	$14.80 	$1.00 	266.35	Friday,December 18,2026	248.35 	Tuesday,April 14,2026	$450.13 				6.76%	Grocery	This is not paid for		100.00%		12.13%			monthly income	$3,710.76
Tissue	$22.25 	8/23/2025	Tuesday,April 14,2026	234	$0.10 	$1.00 	22.25	Sunday,September 14,2025	(211.75)	Tuesday,April 14,2026	$2.89 				1051.69%	Lost tissue	This is paid for		100.00%		0.08%			actual spending last month	$2,020.00
Yard equipment	$438.82 	9/4/2025	Tuesday,April 14,2026	222	$1.98 	$1.00 	438.82	Monday,November 16,2026	216.82 	Tuesday,April 14,2026	$60.13 				50.59%	Yard equipment	This is not paid for		100.00%		1.62%			monthly income - varibale cost	$1,690.76
Boost drink	$640.77 	11/13/2025	Tuesday,April 14,2026	152	$4.22 	$1.00 	640.77	Sunday,August 15,2027	488.77 	Tuesday,April 14,2026	$128.24 				23.72%	Boost	This is not paid for		100.00%		3.46%			bal after varible cost and actual spending	$692.26
Oil change	$102.17 	2/26/2026	Tuesday,April 14,2026	47	$2.17 	$1.00 	102.17	Monday,June 8,2026	55.17 	Tuesday,April 14,2026	$66.13 				46.00%	Oil change	This is not paid for		100.00%		1.78%
Wired mouse	$14.07 	2/22/2026	Tuesday,April 14,2026	51	$0.28 	$1.00 	14.07	Sunday,March 8,2026	(36.93)	Tuesday,April 14,2026	$8.39 				362.47%	Wired mouse	This is paid for		100.00%		0.23%
Gasoline	$113.15 	1/14/2026	Tuesday,April 14,2026	90	$1.26 	$1.00 	113.15	Thursday,May 7,2026	23.15 	Tuesday,April 14,2026	$38.24 				79.54%	Gasoline	This is not paid for		100.00%		1.03%
Lottery	$921.30 	11/25/2024	Tuesday,April 14,2026	505	$1.82 	$1.00 	921.3	Friday,June 4,2027	416.30 	Tuesday,April 14,2026	$55.50 				54.81%	Lottery	This is not paid for		100.00%		1.50%
Rock salt	$85.00 	11/25/2025	Tuesday,April 14,2026	140	$0.61 	$1.00 	85	Wednesday,February 18,2026	(55.00)	Tuesday,April 14,2026	$18.47 				164.71%	Rock salt	This is paid for		100.00%		0.50%
Razor	$32.63 	11/21/2025	Tuesday,April 14,2026	144	$0.23 	$1.00 	32.63	Tuesday,December 23,2025	(111.37)	Tuesday,April 14,2026	$6.89 				441.31%	Razor	This is paid for		100.00%		0.19%
Tissue, paper towel	$41.48 	12/7/2025	Tuesday,April 14,2026	128	$0.32 	$1.00 	41.48	Saturday,January 17,2026	(87)	Tuesday,April 14,2026	$9.86 				308.58%	Tissue, paper towel	This is paid for		100.00%		0.27%
Hair cut	$85.00 	11/25/2025	Tuesday,April 14,2026	140	$0.61 	$1.00 	85	Wednesday,February 18,2026	(55)	Tuesday,April 14,2026	$18.47 				164.71%	Hair cut	This is paid for		100.00%		0.50%
New tires	847.88	9/19/2025	Tuesday,April 14,2026	207	$4.10 	$1.00 	847.88	Friday,January 14,2028	641 	Tuesday,April 14,2026	$124.60 				24.41%	New tires	This is not paid for		100.00%		3.36%
```

In [ ]:
from datetime import datetime, timedelta

TARGET_DAILY_COST = 1.00

# ---- SAFE FLOAT INPUT ----
def get_float(prompt):

    while True:
        try:
            value = float(input(prompt))
            return value
        except ValueError:
            print("Invalid number. Please enter a valid numeric value.")

# ---- SAFE DATE INPUT ----
def get_date(prompt):

    while True:
        try:
            date_str = input(prompt)
            date_value = datetime.strptime(date_str, "%Y-%m-%d")
            return date_value
        except ValueError:
            print("Invalid date. Use format YYYY-MM-DD.")

# ---- USER INPUT ----
monthly_income = get_float("Enter monthly income: $")

daily_income = monthly_income / 30.42

print("Daily income: $", round(daily_income,2))

items = []
today = datetime.today()

while True:

    name = input("\nItem name (press ENTER to finish): ")
    if name == "":
        break

    price = get_float("Price per unit: $")
    quantity = get_float("Quantity: ")

    purchase_date = get_date("Purchase date (YYYY-MM-DD): ")

    total_cost = price * quantity

    days_since = (today - purchase_date).days

    cost_per_day = total_cost / days_since if days_since > 0 else 0

    break_even_days = total_cost / TARGET_DAILY_COST
    break_even_date = purchase_date + timedelta(days=break_even_days)

    remaining_days = break_even_days - days_since

    items.append(cost_per_day)

    print("\n--- Item Summary ---")
    print("Total cost: $", round(total_cost,2))
    print("Days since purchase:", days_since)
    print("Cost per day: $", round(cost_per_day,2))
    print("Break-even date:", break_even_date.date())
    print("Remaining days:", round(remaining_days,2))

# ---- SUMMARY ----
total_daily_cost = sum(items)

remaining_income = daily_income - total_daily_cost

percent_used = (total_daily_cost / daily_income) * 100
percent_remaining = (remaining_income / daily_income) * 100

print("\n====== SUMMARY ======")

print("Daily income: $", round(daily_income,2))
print("Daily cost used: $", round(total_daily_cost,2))
print("Remaining income: $", round(remaining_income,2))

print("Percent used:", round(percent_used,2), "%")
print("Percent remaining:", round(percent_remaining,2), "%")

Enter monthly income: $3710.76
Daily income: $ 121.98

Item name (press ENTER to finish): apple
Price per unit: $1.99
Quantity: 4
Purchase date (YYYY-MM-DD): 2026-04-10

--- Item Summary ---
Total cost: $ 7.96
Days since purchase: 4
Cost per day: $ 1.99
Break-even date: 2026-04-17
Remaining days: 3.96

Item name (press ENTER to finish): oranges
Price per unit: $2.69
Quantity: 4
Purchase date (YYYY-MM-DD): 2026-04-09

--- Item Summary ---
Total cost: $ 10.76
Days since purchase: 5
Cost per day: $ 2.15
Break-even date: 2026-04-19
Remaining days: 5.76

Item name (press ENTER to finish): 

====== SUMMARY ======
Daily income: $ 121.98
Daily cost used: $ 4.14
Remaining income: $ 117.84
Percent used: 3.4 %
Percent remaining: 96.6 %


In [ ]:
import pandas as pd

data = [
    ["Car battery", 311.01, "2026-02-03", 70, 4.44, 1.00, 311.01, "2026-12-11", 241.01, 135.16, "I have not made it", 3.64],
    ["Groceries", 266.35, "2026-03-27", 18, 14.80, 1.00, 266.35, "2026-12-18", 248.35, 450.13, "I have not made it", 12.13],
    ["Tissue", 22.25, "2025-08-23", 234, 0.10, 1.00, 22.25, "2025-09-14", -211.75, 2.89, "I made it", 0.08],
    ["Yard equipment", 438.82, "2025-09-04", 222, 1.98, 1.00, 438.82, "2026-11-16", 216.82, 60.13, "I have not made it", 1.62],
    ["Boost drink", 640.77, "2025-11-13", 152, 4.22, 1.00, 640.77, "2027-08-15", 488.77, 128.24, "I have not made it", 3.46],
    ["Oil change", 102.17, "2026-02-26", 47, 2.17, 1.00, 102.17, "2026-06-08", 55.17, 66.13, "I have not made it", 1.78],
    ["Wired mouse", 14.07, "2026-02-22", 51, 0.28, 1.00, 14.07, "2026-03-08", -36.93, 8.39, "I made it", 0.23],
    ["Gasoline", 113.15, "2026-01-14", 90, 1.26, 1.00, 113.15, "2026-05-07", 23.15, 38.24, "I have not made it", 1.03],
    ["Lottery", 921.30, "2024-11-25", 505, 1.82, 1.00, 921.30, "2027-06-04", 416.30, 55.50, "I have not made it", 1.50],
    ["Rock salt", 85.00, "2025-11-25", 140, 0.61, 1.00, 85.00, "2026-02-18", -55.00, 18.47, "I made it", 0.50],
    ["Razor", 32.63, "2025-11-21", 144, 0.23, 1.00, 32.63, "2025-12-23", -111.37, 6.89, "I made it", 0.19],
    ["Tissue, paper towel", 41.48, "2025-12-07", 128, 0.32, 1.00, 41.48, "2026-01-17", -87.00, 9.86, "I made it", 0.27],
    ["Hair cut", 85.00, "2025-11-25", 140, 0.61, 1.00, 85.00, "2026-02-18", -55.00, 18.47, "I made it", 0.50],
    ["New tires", 847.88, "2025-09-19", 207, 4.10, 1.00, 847.88, "2028-01-14", 641.00, 124.60, "I have not made it", None],
]

columns = [
    "Item", "Total Cost", "Purchase Date", "Days Since Purchase",
    "Cost Per Day", "Target Daily Cost", "Break-even Days",
    "Break-even Date", "Remaining Days", "Per Month",
    "Status", "% Monthly Income"
]

df = pd.DataFrame(data, columns=columns)

# Convert dates to datetime
df["Purchase Date"] = pd.to_datetime(df["Purchase Date"])
df["Break-even Date"] = pd.to_datetime(df["Break-even Date"])

print(df)

monthly_income = 3710.76
variable_cost = 998.50
actual_spending_last_month = 2020.00

remaining_after_variable = monthly_income - variable_cost
balance_after_all = remaining_after_variable - actual_spending_last_month

print("Remaining after variable cost:", remaining_after_variable)
print("Final balance:", balance_after_all)

In [ ]:
import pandas as pd
from datetime import datetime, timedelta

# Data
data = [
    ["New battery", 311.01, "2026-02-03"],


    ["Costco", 210.80, "2026-03-27"],
    ["Loss tissue", 22.25, "2025-08-23"],
    ["Yard equipment", 438.82, "2025-09-04"],
    ["Boost", 640.77, "2025-11-13"],
    ["Oil change", 102.17, "2026-02-26"],
    ["Wired mouse", 14.07, "2026-02-22"],
    ["Gasoline", 113.15, "2026-01-14"],
    ["Lottery", 921.30, "2024-11-25"],
    ["Rock salt", 85.00, "2025-11-25"],
]

df = pd.DataFrame(data, columns=["Item", "Total Cost", "Purchase Date"])

# Convert dates
df["Purchase Date"] = pd.to_datetime(df["Purchase Date"])

# Today's date
today = pd.Timestamp("2026-04-11")

# Calculations
df["Days Since Purchase"] = (today - df["Purchase Date"]).dt.days
df["Cost Per Day"] = df["Total Cost"] / df["Days Since Purchase"]

target_daily_cost = 1.00
df["Target Daily Cost"] = target_daily_cost

# Break-even days (cost ÷ target daily cost)
df["Break-even Days"] = df["Total Cost"] / target_daily_cost

# Break-even date
df["Break-even Date"] = df["Purchase Date"] + pd.to_timedelta(df["Break-even Days"], unit="D")

# Remaining days
df["Remaining Days"] = df["Break-even Days"] - df["Days Since Purchase"]

# Formatting
pd.options.display.float_format = '{:,.2f}'.format

print(df)

             Item  Total Cost Purchase Date  Days Since Purchase  \
0     New battery      311.01    2026-02-03                   67   
1          Costco      210.80    2026-03-27                   15   
2     Loss tissue       22.25    2025-08-23                  231   
3  Yard equipment      438.82    2025-09-04                  219   
4           Boost      640.77    2025-11-13                  149   
5      Oil change      102.17    2026-02-26                   44   
6     Wired mouse       14.07    2026-02-22                   48   
7        Gasoline      113.15    2026-01-14                   87   
8         Lottery      921.30    2024-11-25                  502   
9       Rock salt       85.00    2025-11-25                  137   

   Cost Per Day  Target Daily Cost  Break-even Days     Break-even Date  \
0          4.64               1.00           311.01 2026-12-11 00:14:24   
1         14.05               1.00           210.80 2026-10-23 19:12:00   
2          0.10           

In [ ]:
# Display the first few rows of the created DataFrame
display(df_from_text.head())

,Item,Total Cost,Purchase Date,Days Since Purchase,Cost Per Day,Target Daily Cost,Break-even Days,Break-even Date,Remaining Days,Per Month,Status,% Monthly Income
0,Car battery,311.01,2026-02-03,70,4.44,1.0,311.01,2026-12-11,241.01,135.16,This is not paid for,3.64
1,Groceries,266.35,2026-03-27,18,14.80,1.0,266.35,2026-12-18,248.35,450.13,This is not paid for,12.13
2,Tissue,22.25,2025-08-23,234,0.10,1.0,22.25,2025-09-14,-211.75,2.89,This is paid for,0.08
3,Yard equipment,438.82,2025-09-04,222,1.98,1.0,438.82,2026-11-16,216.82,60.13,This is not paid for,1.62
4,Boost drink,640.77,2025-11-13,152,4.22,1.0,640.77,2027-08-15,488.77,128.24,This is not paid for,3.46


In [ ]:
def show_summary(df):

    if len(df) == 0:
        print("\nNo purchases recorded.")
        return

    # Use format='mixed' to handle potentially inconsistent date formats
    # Use errors='coerce' to turn unparseable dates into NaT, ensuring datetime dtype
    df["Purchase Date"] = pd.to_datetime(df["Purchase Date"], format='mixed', errors='coerce')

    today = datetime.today().date()

    df["Days Since Purchase"] = (today - df["Purchase Date"].dt.date).dt.days
    df["Cost Per Day"] = df["Total Cost"] / df["Days Since Purchase"].replace(0,1)

    total_spent = df["Total Cost"].sum()
    total_items = len(df)

    most_expensive = df.loc[df["Total Cost"].idxmax()]

    avg_cost_day = df["Cost Per Day"].mean()

    print("\n========== SUMMARY ==========")
    print("Total Items:", total_items)
    print("Total Money Spent: $", round(total_spent,2))
    print("Average Cost Per Day: $", round(avg_cost_day,2))
    print("Most Expensive Item:", most_expensive["Item"],
          "($"+str(round(most_expensive["Total Cost"],2))+")")
    print("=============================\n")

In [ ]:
def apply(criteria, n):
    count = 0
    for i in range(n+1):
         if criteria(i):
            count += 1
    return count


# What this function does:

# criteria -> a function that tests a condition (like “is it even?”)

# n -> the upper limit of numbers to test

# How it works:

# count = 0
# Starts a counter at zero.

# for i in range(n + 1)
# Loops through numbers from 0 to n, including n.

# if criteria(i):
# Calls the criteria function on each number.
# If it returns True, then…

# count += 1
# …increase the counter.

# return count
# After the loop finishes, return how many numbers satisfied the criteria.


def is_even(x):
    return x % 2 == 0

# This returns True if x is divisible by 2, otherwise False.

# So it is used as a test for “Is this number even?”


print(apply(is_even, 10))

# This asks:

# “How many numbers from 0 to 10 are even?”

# Even numbers between 0 and 10:

# 0, 2, 4, 6, 8, 10 -> 6 numbers

# Final Output
# 6

6


In [ ]:
import random

import string

chars = list(string.ascii_letters + string.digits + string.punctuation)
print(chars)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']


In [ ]:
numbers = [198, 117, 122, 127]

avg = 0

for i, value in enumerate(numbers, 1):
    avg = ((avg * (i - 1)) + value) / i
    print("Running average:", avg)

Running average: 198.0
Running average: 157.5
Running average: 145.66666666666666
Running average: 141.0


In [ ]:
credit_limit = float(input("Enter your available credit: "))
amount_owed = float(input("Enter credit limit: "))

difference = credit_limit - amount_owed
print(f"You owe ${difference:,.2f}")

original_amount = 16896.61
print(f"Original amount: ${original_amount:,.2f}")

current_equity = difference + original_amount
print(f"Current equity: ${current_equity:,.2f}")

ownership = (current_equity / original_amount) * 100
print(f"Ownership: {ownership:.2f}%")


Enter your available credit: 641.61
Enter credit limit: 2900
You owe $-2,258.39
Original amount: $16,896.61
Current equity: $14,638.22
Ownership: 86.63%


In [ ]:
from datetime import date
current_miles = 51914
start_miles = 51564
miles_driven = current_miles - start_miles
print(f"You have driven {miles_driven}")


start_date = date(2025, 12, 14)
end_date = date(2026, 3, 27)
days = (end_date - start_date).days
print(f"Amount of time driven in days: {days}")

per_day = miles_driven / days
print(f"Miles per day: {per_day:.2f}")


daily_income = 120.37
auto_allowance = daily_income * .02
print(f"Auto allowance: ${auto_allowance:.2f}")

depreciation_expense = per_day * auto_allowance
print(f"Depreciation expense: ${depreciation_expense:.2f}")

total_miles_driven = current_miles - start_miles
print(f"Total miles driven: {total_miles_driven}")
print
total_cost = total_miles_driven * auto_allowance
print(f"Total cost: ${total_cost:.2f}")






You have driven 350
Amount of time driven in days: 103
Miles per day: 3.40
Auto allowance: $2.41
Depreciation expense: $8.18
Total miles driven: 350
Total cost: $842.59


In [ ]:
from datetime import date
first_day = date(2026, 1, 1)
today = date.today()
days_apart = today - first_day
print(f"Days apart: {days_apart.days}")
cash_out = float(input("How much did you spend for groceries? "))
last = float(input("How long do you expect the groceries to last? "))
print(f"Number of days groceries are expected to last: {last}")
print(f"Cash out: ${cash_out:,.2f}")
actual = cash_out / days_apart.days
print(f"Actual daily cost: ${actual:,.2f}")
actual2 = cash_out / last
print(f"Projected daily cost: ${actual2:,.2f}")
if actual > actual2:
    print("You are spending more than the projected rate.")
    print(f"Difference: ${actual - actual2:,.2f}")
else:
    print("You are spending less than the projected rate.")
    print(f"Difference: ${actual2 - actual:,.2f}")




Days apart: 24
How much did you spend for groceries? 368.98
How long do you expect the groceries to last? 20
Number of days groceries are expected to last: 20.0
Cash out: $368.98
Actual daily cost: $15.37
Projected daily cost: $18.45
You are spending less than the projected rate.
Difference: $3.07


In [ ]:
# CURRENT FINANCE

current_balance = float(input("Enter your current cash balance: "))
one_creditcard = float(input("Enter your first credit card amount: "))
two_creditcard = float(input("Enter your second credit card amount: "))
beginning_balance = float(input("What was your past balance? "))
total_credit = one_creditcard + two_creditcard
print(f"Total credit card payments: ${total_credit:,.2f}")
left_over = current_balance - total_credit
print(f"Your new balance after full credit is paid: ${left_over:,.2f}")

# Incoming income
ss = float(input("Enter your upcoming Social Security payment: "))
#pension = float(input("Enter your upcoming pension payment: "))


upcoming_income = ss
print(f"Expected income: ${upcoming_income:,.2f}")
balance = left_over + upcoming_income
print(f"Balance after income: ${balance:,.2f}")




Enter your current cash balance: 16528.86
Enter your first credit card amount: 383.66
Enter your second credit card amount: 500
What was your past balance? 16896.61
Total credit card payments: $883.66
Your new balance after full credit is paid: $15,645.20
Enter your upcoming Social Security payment: 2253
Expected income: $2,253.00
Balance after income: $17,898.20


High balance: $16,896.61 
Current balance: $12,590.24
Credit card payments: $1,333.36
New balance: $11,256.88
Enter your first income: 2253
First income: $2,253.00
Enter your second income: 1457
Second income: $1,457.00
Enter your third income: 2253
Third income: $2,253.00
Total income: $5,963.00
Loss from spending: $-5,639.73
Your net position is $323.27
Enter your next month bills: 1961.34
Estimated bills next month $1,961.34
Cashflow: $-1,638.07
Enter your march income: 2253
March income is $2,253.00
Enter your april income: 56
April income is $56.00
Total income for Feb, Mar, Apr is $8,272.00
Net cashflow: $-3,330.73


In [ ]:
goal = 16896.61
print(f"High balance: ${goal:,.2f} ")
current_balance = 12590.24
credit_card_payments = 1333.36
print(f"Current balance: ${current_balance:,.2f}")
print(f"Credit card payments: ${credit_card_payments:,.2f}")
new_balance = current_balance - credit_card_payments
print(f"New balance: ${new_balance:,.2f}")
first_income = float(input ("Enter your first income: "))
print(f"First income: ${first_income:,.2f}")
second_income = float(input ("Enter your second income: "))
print(f"Second income: ${second_income:,.2f}")
third_income = float(input ("Enter your third income: "))
print(f"Third income: ${third_income:,.2f}")
all_income = first_income + second_income + third_income
print(f"Total income: ${all_income:,.2f}")
loss_from_spending = new_balance - goal
print(f"Loss from spending: ${loss_from_spending:,.2f}")
net_position = all_income + loss_from_spending
print(f"Your net position is ${net_position:,.2f}")
next_month_bills = float(input ("Enter your next month bills: "))
print(f"Estimated bills next month ${next_month_bills:,.2f}")
cashflow = net_position - next_month_bills
print(f"Cashflow: ${cashflow:,.2f}")
march_income = float(input("Enter your march income: "))
print(f"March income is ${march_income:,.2f}")
april_income = float(input("Enter your april income: "))
print(f"April income is ${april_income:,.2f}")
all_income1 = all_income + march_income + april_income
print(f"Total income for Feb, Mar, Apr is ${all_income1:,.2f}")
loss_from_spending1 = loss_from_spending + march_income + april_income
print(f"Net cashflow: ${loss_from_spending1:,.2f}")





In [ ]:
# CASH PROJECTIONS- EARY RETIREMENT
goal = float(input("Enter your target (high) balance: "))
print(f"High balance: ${goal:,.2f}")

# CURRENT POSITION
current_balance = float(input("Enter your current balance: "))
credit_card_payments = float(input("Enter total credit card payments: "))

print(f"Current balance: ${current_balance:,.2f}")
print(f"Credit card payments: ${credit_card_payments:,.2f}")

new_balance = current_balance - credit_card_payments
print(f"New balance: ${new_balance:,.2f}")

# INCOME SOURCES
first_income = float(input("Enter your first income: "))
print(f"First income: ${first_income:,.2f}")

second_income = float(input("Enter your second income: "))
print(f"Second income: ${second_income:,.2f}")

third_income = float(input("Enter your third income: "))
print(f"Third income: ${third_income:,.2f}")

all_income = first_income + second_income + third_income
print(f"Total income: ${all_income:,.2f}")

# LOSS / GAIN FROM SPENDING
loss_from_spending = new_balance - goal
print(f"Loss from spending: ${loss_from_spending:,.2f}")

net_position = all_income + loss_from_spending
print(f"Net position: ${net_position:,.2f}")

# NEXT MONTH
next_month_bills = float(input("Estimated monthly bills: "))
print(f"Estimated bills next month: ${next_month_bills:,.2f}")


cashflow = net_position - next_month_bills
print(f"Cashflow: ${cashflow:,.2f}")

# FUTURE INCOME
march_income = float(input("Enter your March income: "))
print(f"March income is: ${march_income:,.2f}")

april_income = float(input("Enter your April income: "))
print(f"April income is: ${april_income:,.2f}")

all_income1 = march_income + april_income
print(f"Expected income for Mar, Apr: ${all_income1:,.2f}")
three_month_bills = 810.64 * 3
print(f"Estimated bills next 3 months: ${three_month_bills:,.2f}")
#loss_from_spending1 = loss_from_spending + march_income + april_income
result =all_income1 - three_month_bills

print(f"Net cashflow: ${result:,.2f}")


Enter your target (high) balance: 16896.61
High balance: $16,896.61
Enter your current balance: 12590.24
Enter total credit card payments: 1333.36
Current balance: $12,590.24
Credit card payments: $1,333.36
New balance: $11,256.88
Enter your first income: 2253
First income: $2,253.00
Enter your second income: 1457.76
Second income: $1,457.76
Enter your third income: 2253
Third income: $2,253.00
Total income: $5,963.76
Loss from spending: $-5,639.73
Net position: $324.03
Estimated monthly bills: 810.64
Estimated bills next month: $810.64
Cashflow: $-486.61
Enter your March income: 3710.76
March income is: $3,710.76
Enter your April income: 3710.76
April income is: $3,710.76
Expected income for Mar, Apr: $7,421.52
Estimated bills next 3 months: $2,431.92
Net cashflow: $4,989.60


In [ ]:
from datetime import date

item = "Rock Salt"
cost = 18.00+13.12

start_date = date(2026, 1, 16)
end_date = date(2026, 3, 25)

# Calculate number of days
days = (end_date - start_date).days

cost_per_day = cost / days
#print(f"Cost per day: ${cost_per_day:.2f}")

print(f"Item: {item}")
print(f"Rate: ${cost_per_day:.2f} per day")
print(f"Start Date: {start_date}")
print(f"End Date: {end_date}")
print(f"Days Charged: {days}")
print(f"Original Cost: ${cost:.2f}")
percent = cost_per_day / 120.37 * 100
print(f"Percent of daily income: {percent:.2f}% ")


Item: Rock Salt
Rate: $0.46 per day
Start Date: 2026-01-16
End Date: 2026-03-25
Days Charged: 68
Original Cost: $31.12
Percent of daily income: 0.38% 


In [ ]:
!pip install camelcase
import camelcase

c = camelcase.CamelCase()

txt = "hello world"

print(c.hump(txt))

Hello World


In [ ]:
#groceries
import datetime

grocery_spending = float(input("How much did you spend on groceries? "))
print(f"You spent ${grocery_spending:,.2f} on groceries")
print("\n")
time = input("What was the first day of grocery shopping? ")
time = datetime.datetime.strptime(time, "%m/%d/%Y")
print(f"You bought groceries on {time}")
print("\n")
total_per_day = input("What is today's date? %m/%d/%Y ")
total_per_day = datetime.datetime.strptime(total_per_day, "%m/%d/%Y")
print(f"Today is {total_per_day}")
print("\n")
days_apart = total_per_day - time
print(f"It has been {days_apart.days} days since you bought groceries")
print("\n")

if days_apart.days > 0:
    average_per_day = grocery_spending / days_apart.days
    print(f"You are spending ${average_per_day:,.2f} on groceries per day")
else:
    print("Cannot calculate average per day: Days apart is zero.")
print("\n")

income_per_day = float(input("What is your income per day? "))
print(f"Your income per day is ${income_per_day:,.2f}")
print("\n")
income_per_month = income_per_day * 30.42
print(f"Your income per month is ${income_per_month:,.2f}")
print("\n")

duration = float(input("Estimated days for food to last? "))

if duration > 0:

    projected_cost = grocery_spending / duration
    print(f"You need to spend ${projected_cost:,.2f} on groceries per day to make it last {duration} days")
    estimated_date = total_per_day + datetime.timedelta(days=duration)

else:
    print("Cannot project cost: Duration is zero.")


How much did you spend on groceries? 368.98
You spent $368.98 on groceries


What was the first day of grocery shopping? 01/01/2026
You bought groceries on 2026-01-01 00:00:00


What is today's date? %m/%d/%Y 01/15/2026
Today is 2026-01-15 00:00:00


It has been 14 days since you bought groceries


You spent $26.36 on groceries per day


What is your income per day? 120.37
Your income per day is $120.37


Your income per month is $3,661.66


Estimated days for food to last? 27
You need to spend $13.67 on groceries per day to make it last 27.0 days


In [ ]:
day = 5
match day:
  case 1:
    print("Monday")
  case 2:
    print("Tuesday")
  case 3:
    print("Wednesday")
  case 4:
    print("Thursday")
  case 5:
    print("Friday")
  case 6:
    print("Saturday")
  case 7:
    print("Sunday")
  case _:
    print("Invalid day")

Friday


In [ ]:
day = 7
match day:
  case 1 | 2 | 3 | 4 | 5:
    print("Today is a weekday")
  case 6 | 7:
    print("I love weekends!")

I love weekends!


In [ ]:
d = {"a": 10, "b": 1, "c": 22}
#d = {"a" :10, "b" :1, "c" :22}
d.items()
#dict_items([("a", 10), ("c", 22), ("b", 1)])
#sorted(d.items())


#d = {"a": 10, "b": 1, "c": 22}

print(d.items())

dict_items([('a', 10), ('b', 1), ('c', 22)])


In [ ]:
d = {"a":10, "b":1, "c":22}
t = sorted(d.items())
print(t)

for k, v in sorted(d.items()):
  print(k, v)


[('a', 10), ('b', 1), ('c', 22)]
a 10
b 1
c 22


In [ ]:
c = {"a":10, "b":1, "c":22}
tmp = list()
for k, v in c.items():
  tmp.append((v, k))
  print(tmp)


0

[(10, 'a')]
[(10, 'a'), (1, 'b')]
[(10, 'a'), (1, 'b'), (22, 'c')]


In [ ]:


line = "first;second;third"
thing = line.split()
print(thing)
print("\n")
thing = line.split(";")
print(thing)

['first;second;third']


['first', 'second', 'third']


In [ ]:
abc = "With three words"
stuff = abc.split()
print(stuff)
print(len(stuff))

print((stuff[0]))

print(stuff)
for w in stuff:
  print(w)


['With', 'three', 'words']
3
With
['With', 'three', 'words']
With
three
words


In [ ]:
from string import digits
digits  = [5, 1, 2, 3]
for i in digits:
  for j in digits:
    for k in digits:
      for l in digits:
        print(i, j, k, l)
if [i, j, k, l] == digits:
 print(digits)

5 5 5 5
5 5 5 1
5 5 5 2
5 5 5 3
5 5 1 5
5 5 1 1
5 5 1 2
5 5 1 3
5 5 2 5
5 5 2 1
5 5 2 2
5 5 2 3
5 5 3 5
5 5 3 1
5 5 3 2
5 5 3 3
5 1 5 5
5 1 5 1
5 1 5 2
5 1 5 3
5 1 1 5
5 1 1 1
5 1 1 2
5 1 1 3
5 1 2 5
5 1 2 1
5 1 2 2
5 1 2 3
5 1 3 5
5 1 3 1
5 1 3 2
5 1 3 3
5 2 5 5
5 2 5 1
5 2 5 2
5 2 5 3
5 2 1 5
5 2 1 1
5 2 1 2
5 2 1 3
5 2 2 5
5 2 2 1
5 2 2 2
5 2 2 3
5 2 3 5
5 2 3 1
5 2 3 2
5 2 3 3
5 3 5 5
5 3 5 1
5 3 5 2
5 3 5 3
5 3 1 5
5 3 1 1
5 3 1 2
5 3 1 3
5 3 2 5
5 3 2 1
5 3 2 2
5 3 2 3
5 3 3 5
5 3 3 1
5 3 3 2
5 3 3 3
1 5 5 5
1 5 5 1
1 5 5 2
1 5 5 3
1 5 1 5
1 5 1 1
1 5 1 2
1 5 1 3
1 5 2 5
1 5 2 1
1 5 2 2
1 5 2 3
1 5 3 5
1 5 3 1
1 5 3 2
1 5 3 3
1 1 5 5
1 1 5 1
1 1 5 2
1 1 5 3
1 1 1 5
1 1 1 1
1 1 1 2
1 1 1 3
1 1 2 5
1 1 2 1
1 1 2 2
1 1 2 3
1 1 3 5
1 1 3 1
1 1 3 2
1 1 3 3
1 2 5 5
1 2 5 1
1 2 5 2
1 2 5 3
1 2 1 5
1 2 1 1
1 2 1 2
1 2 1 3
1 2 2 5
1 2 2 1
1 2 2 2
1 2 2 3
1 2 3 5
1 2 3 1
1 2 3 2
1 2 3 3
1 3 5 5
1 3 5 1
1 3 5 2
1 3 5 3
1 3 1 5
1 3 1 1
1 3 1 2
1 3 1 3
1 3 2 5
1 3 2 1
1 3 2 2
1 3 2 3
1 3 3 5


In [ ]:
name  = input("What is your name? ")
if name == "":
    print("You didn't enter a name")
else:
    print(f"Hello {name}")
#
    print("\n")








What is your name? 
You didn't enter a name


In [ ]:
word = input("Enter a word:")
word1 = input("Enter a word: ")

if word1 == word:
    print("Both words are the same.")
elif word < word1:
    print(f"The word '{word}' comes before the word '{word1}'.")
else:
    print(f"The word '{word}' comes after the word' {word1}'.")


Enter a word:pot
Enter a word: vote
The word 'pot' comes before the word 'vote'.


In [ ]:
for_sale = True

if for_sale:
    print("This item is for sale")
else:
    print("This item is NOT for sale")



This item is for sale


In [ ]:

#Save
original_cash = 16896.61
print(f"Your highest balance ---> ${original_cash:,.2f} ")
print("\n")
pay_bill = float(input("How much will be paid toward bills? "))
print(f"Bill payment---> ${pay_bill:.2f} ")

cash = float(input("How much cash do you have? "))
print(f"First Cash Balance is ${cash:,.2f} ")
loss = cash - pay_bill - original_cash
print(f"Losses ${loss:,.2f} ")
next_cash = cash - pay_bill
print(f"Second Cash Balance ${next_cash:,.2f} ")
print("\n")

next_payments = 2204 + 1457.76
print(f"Next payments ${next_payments:,.2f} ")
deficit = loss + next_payments
print(f"My deficit is ${deficit:,.2f} ")
print("\n")


Your highest balance ---> $16,896.61 


How much will be paid toward bills? 180.96
Bill payment---> $180.96 
How much cash do you have? 12615.53
First Cash Balance is $12,615.53 
Losses $-4,462.04 
Second Cash Balance $12,434.57 


Next payments $3,661.76 
My deficit is $-800.28 




In [ ]:
friends = [("Rachel", 19),
           ("(Monica", 18),
           ("Phoebe", 17),
           ("Joey", 16),
           ("Chandler", 21),
           ("Ross", 20)]
age = lambda data:data[1] >= 18


drinking_buddies = list(filter(age, friends))
#print(drinking_buddies)

for i in drinking_buddies:
    print(i)



('Rachel', 19)
('(Monica', 18)
('Chandler', 21)
('Ross', 20)


In [ ]:
def loud(text):
    return text.upper()
def quiet(text):
    return text.lower()
def hello(func):
    text = func("Hello")
    print(text)

def quiet(text):
    return text.lower

hello(loud)
hello(quiet)

HELLO
<built-in method lower of str object at 0x7a71ae29c360>


In [ ]:
foods = list()
while True:
    food = input("What food do you like? ")
    if food == "":
        break
    foods.append(food)
print(foods)





What food do you like? chicken
What food do you like? hamburger
What food do you like? 
['chicken', 'hamburger']


In [ ]:
#Current Finance
high_balance = float(input("What was your higest balance? "))
current_balance = float(input("What is your current balance? "))
first_loss = current_balance - high_balance
print(f"Your first loss was ${first_loss:,.2f}")

credit_balance = float(input("How much is your total credit card balance? "))
new_balance = current_balance - credit_balance
print(f"Your new balance is ${new_balance:,.2f}")



second_loss = new_balance - high_balance
print(f"Your second loss is ${second_loss:,.2f}")

social_security = float(input("How much is your next social security? "))
#print(f"Your social security is ${social_security:,.2f}")
pension = float(input("How much is your next pension? "))
#print(f"Your pension is ${pension:,.2f}")
deficit = second_loss + social_security + pension
print(f"Your deficit is ${deficit:,.2f}")

What was your higest balance? 16896.61
What is your current balance? 12615.53
Your first loss was $-4,281.08
How much is your total credit card balance? 37.98
Your new balance is $12,577.55
Your second loss is $-4,319.06
How much is your next social security? 2204
How much is your next pension? 1457.76
Your deficit is $-657.30


In [ ]:
nums = [1, 2, 3, 4]
nums.reverse()
print(nums)


[4, 3, 2, 1]


In [ ]:
nums = [1, 2, 3]
new = nums.reverse()
print(new)   # ❌ None


None


In [ ]:
nums = [1, 2, 3, 4]
rev = reversed(nums)

print(list(rev))
print(nums)


[4, 3, 2, 1]
[1, 2, 3, 4]


In [ ]:
#Most recent

bb = 16896.16
print(f"Your highest balance ---> ${bb:,.2f} ")
eb = 13248.19
print("\n")
firstLoss = eb - bb
cb = 15452.19 + 1457.76

print(f"Cash balance ----> {cb:,.2f} ")
print("\n")
firstLoss = eb - bb
print(f"Your first loss was ${firstLoss:,.2f} ")
print("\n")
credit = 2815.44
new_bal = cb - credit
print(f"After chase credit card one is paid ${new_bal:,.2f} ")

#print(f"Balance after lowest credit is paid ${new_bal:,.2f}")
total_credit = 2815.44+1478.98

print(f"Total credit balance is ${total_credit:,.2f} ")
print("\n")

sb = eb - total_credit
print(f"Balance to ${sb:,.2f} from ${eb:,.2f} ")
print("\n")
ss = 2204
ab = ss + sb
print(f"Adjusted balance ${ab:,.2f} ")
second_Loss = ab - bb
print("\n")

print(f"Your second loss is ${second_Loss:,.2f} ")
p = 1457.76
print("\n")
print(f"Your pension is ${p:,.2f} ")
jd = second_Loss + p + ss
print("\n")
print(f"You will have a deficit in January of ${jd:,.2f} ")

print(f"Your first loss was ${firstLoss:,.2f} ")
print("\n")

credit = 2815.44+1478.98
print(f"Total credit balance is ${credit:,.2f} ")
print("\n")

sb = eb - credit
print(f"After credit cards are paid ${sb:,.2f} ")
print("\n")
ss = 2204
ab = ss + sb
print(f"Adjusted balance ${ab:,.2f} ")
second_Loss = ab - bb

print("\n")

print(f"Your second loss is ${second_Loss:,.2f} ")
p = 1457.76
print("\n")
print(f"Your pension is ${p:,.2f} ")
jd = second_Loss + p + ss
#print("\n")
#print(f"You will have a deficit in January of ${jd:,.2f} ")





Your highest balance ---> $16,896.16 


Cash balance ----> 16,909.95 


Your first loss was $-3,647.97 


After chase credit card one is paid $14,094.51 
Total credit balance is $4,294.42 


Balance to $8,953.77 from $13,248.19 


Adjusted balance $11,157.77 


Your second loss is $-5,738.39 


Your pension is $1,457.76 


You will have a deficit in January of $-2,076.63 
Your first loss was $-3,647.97 


Total credit balance is $4,294.42 


After credit cards are paid $8,953.77 


Adjusted balance $11,157.77 


Your second loss is $-5,738.39 


Your pension is $1,457.76 


In [ ]:
#Most recent
"""
Created on Wed Dec 31 10:23:44 2025

@author: lewis
"""

bb = 16896.16
print(f"Your highest balance ---> ${bb:,.2f} ")
eb = 13248.19
print("\n")
firstLoss = eb - bb
cb = 15452.19 + 1457.76
tax_payments = 1500 + 975 + 700 + 100 + 100 +705 +800 + 625.40 + 100 + 800 + 625.40 + 1260.01 + 564 + 764 + 140 + 140 + 600 + 150
print(f"Total tax payments---> ${tax_payments:,.2f} ")
print(f"Cash balance ----> {cb:,.2f} ")
pe = cb - tax_payments
print(f"Projected Equity---> {pe:,.2f} ")
firstLoss = eb - bb
print(f"The first loss was ${firstLoss:,.2f} ")
print("\n")
credit = 2815.44
new_bal = cb - credit
print(f"After chase credit card one is paid ${new_bal:,.2f} ")

#print(f"Balance after lowest credit is paid ${new_bal:,.2f}")
total_credit = 2815.44+1478.98

print(f"Total credit balance is ${total_credit:,.2f} ")
print("\n")

sb = eb - total_credit
print(f"Balance to ${sb:,.2f} from ${eb:,.2f} ")
print("\n")
ss = 2204
ab = ss + sb
print(f"Adjusted balance ${ab:,.2f} ")
second_Loss = ab - bb
print("\n")

print(f"The second loss is ${second_Loss:,.2f} ")
p = 1457.76
print("\n")
print(f"Your pension is ${p:,.2f} ")
jd = second_Loss + p + ss
print("\n")
print(f"You will have a deficit in January of ${jd:,.2f} ")

print(f"Your first loss was ${firstLoss:,.2f} ")
print("\n")

credit = 2815.44+1478.98
print(f"Total credit balance is ${credit:,.2f} ")
print("\n")

sb = eb - credit
print(f"After credit cards are paid ${sb:,.2f} ")
print("\n")
ss = 2204
ab = ss + sb
print(f"Adjusted balance ${ab:,.2f} ")
second_Loss = ab - bb

print("\n")

#
print(f"Your second loss is ${second_Loss:,.2f} ")
p = 1457.76
print("\n")
print(f"Your pension is ${p:,.2f} ")
jd = second_Loss + p + ss
#print("\n")
#print(f"You will have a deficit in January of ${jd:,.2f} ")





Your highest balance ---> $16,896.16 


Total tax payments---> $10,648.81 
Cash balance ----> 16,909.95 
Projected Equity---> 6,261.14 
The first loss was $-3,647.97 


After chase credit card one is paid $14,094.51 
Total credit balance is $4,294.42 


Balance to $8,953.77 from $13,248.19 


Adjusted balance $11,157.77 


The second loss is $-5,738.39 


Your pension is $1,457.76 


You will have a deficit in January of $-2,076.63 
Your first loss was $-3,647.97 


Total credit balance is $4,294.42 


After credit cards are paid $8,953.77 


Adjusted balance $11,157.77 


Your second loss is $-5,738.39 


Your pension is $1,457.76 


In [ ]:
#Class Learning
import random

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def speak(self):
        print("I am a person")

    def __str__(self):
        return f"Person: {self.name}, {self.age}"

class Student(Person):
    def __init__(self, name, age, major=None):
        super().__init__(name, age)
        self.major = major

    def change_major(self, major):
        self.major = major

    def speak(self):
        r = random.random()
        if r < 0.25:
            print("I have homework")
        elif r < 0.5:
            print("I need sleep")
        elif r < 0.75:
            print("I should eat")
        else:
            print("I'm still zooming")

    def __str__(self):
        return f"Student: {self.name}, {self.age}, {self.major}"


s = Student("Greg", 70, "Accounting")
print(s)
s.speak()

s = Student("Pam", 64, "Art")
print(s)
s.speak()

s = Student("Jim", 24,"Computer Science")
print(s)
s.speak()



Student: Greg, 70, Accounting
I have homework
Student: Pam, 64, Art
I need sleep
Student: Jim, 24, Computer Science
I need sleep


In [ ]:
class Animal:
  pass

class Rabbit(Animal):
  tag = 1
  def __init__(self, age, parent1=None, parent2=None):
    # Animal.__init__(self, age) # Removed: Animal class provided does not have an __init__ that takes 'age'
    self.age = age # Store age directly in Rabbit
    self.parent1 = parent1
    self.parent2 = parent2
    self.rid = Rabbit.tag
    Rabbit.tag += 1
  def get_rid(self):
    return str(self.rid) .zfill(5)
  def get_parent(self):
    return self.parent1
  def get_parent2(self):
    return self.parent2
  def __add__(self, other):
    return Rabbit(0, self, other)

  # The following __add__ method is a duplicate and contains an undefined variable 'parents_opp'.
  # It will be overridden by the first __add__ definition anyway. Commenting out for now.
  # def __add__(self, other):
  #   # returning object of same type as this class
  #   return Rabbit(0, self, other)
  #   #recall Rabbit's__init__(self, age, parent1=None, parent2=None)
  #   parents_same = (self.parent1.rid == other.parent1.rid
  #   and self.parent2.rid == other.parent2.rid)
  #   return parents_same or parents_opp

r1 = Rabbit(3)
r2 = Rabbit(4)
r3 = Rabbit(5)
print("r1 parent1:", r1.get_parent())
print("r1 parent2:", r1.get_parent2())

r1 parent1: None
r1 parent2: None


In [ ]:
text = "hello"
print(text[::-1])


olleh


In [ ]:
nums = [1, 2, 3]
new_nums = nums[::-1]
print(new_nums)

[3, 2, 1]


In [ ]:



  def __init__(self, xval, yval):
        self.x = xval
        self.y = yval
c = Coordinate(3, 4)
orig = Coordinate(0, 0)
print(c.x)
print(orig.x)




3
0


In [ ]:

try:
  a = int(input("Tell me one number: "))
  b = int(input("Tell me another number: "))
  print("a/b = ", a/b)
  print("a+b = ", a+b)
except ValueError:
  print("Could not convert data to a number.")
except ZeroDivisionError:
  print("Can't divide by zero")
  print("a/b = infinity")
  print("a+b = ", a+b)

except:
  print("Something went very wrong.")
#




Tell me one number: 46
Tell me another number: 0
Can't divide by zero
a/b = infinity
a+b =  46


In [ ]:
cube = int(input("Enter an integer: "))
for guess in range (abs(cube)+1):
    if guess**3 >= abs(cube):
        break
if guess **3 != abs(cube):
    print(cube, "is not a perfect cube")
else:
    if cube < 0:
        guess = -guess
    print("Cube root of "+str(cube)+" is "+str(guess))

Enter an integer: 27
Cube root of 27 is 3


In [ ]:
guess = 0
neg_flag = False
x = int(input("Enter a positive integer "))
if x < 0:
     neg_flag = True
while guess**2 < x:
    guess = guess + 1
if guess**2 == x:
        print(f"The square root of {x} is {guess}")
else:
      print(f"{x} is not a perfect square")
      if neg_flag:
        print(f"Just checking...did you mean {-x}")
#


Enter a positive integer 4
The square root of 4 is 2


In [ ]:
import threading

import time


def walk_dog():
    time.sleep(8)
    print("I'm walking my dog")

def take_out_trash():
    time.sleep(2)
    print("I'm taking out the trash")

def wash_dishes():
    time.sleep(4)
    print("I'm washing the dishes")

def get_mail():
  time.sleep(3)
  print("I'm getting my mail")

def do_homework():
    time.sleep(6)
    print("I'm doing my homework")

walk_dog()
take_out_trash()
wash_dishes()
get_mail()
do_homework()

chore1 = threading.Thread(target=walk_dog)
chore1.start()
chore2 = threading.Thread(target=take_out_trash)
chore2.start()
chore3 = threading.Thread(target=wash_dishes)
chore3.start()
chore4 = threading.Thread(target=get_mail)
chore4.start()

print("I'm done")

I'm walking my dog
I'm taking out the trash
I'm washing the dishes
I'm getting my mail
I'm doing my homework


In [ ]:
mysum = 0
start = 3
end = 5

for i in range(start, end):
    print("i =", i)
    mysum += i

print(mysum)


i = 3
i = 4
7


In [ ]:
mysum = 0
start = 3
end = 5
for i in range(start, end):
    mysum += i
print(mysum)


mysum = 0
start = 3
end = 5
for i in range(start, end+1):
    print("i=", i)
    mysum += i
print(mysum)

7
i= 3
i= 4
i= 5
12


In [ ]:
class Employee:
    def __init__(self, name, position):
        self.name = name
        self.position = position

    def get_info(self):
      return f"{self.name} = {self.position}"

    @staticmethod
    def is_valid_position(position):
        valid_positions = ["Manager", "Cashier", "Cook", "Janitor"]
        return position in valid_positions

print(Employee.is_valid_position("Cook"))

True


In [ ]:
store = {"shirt": 20.00, "pants": 25.00, "jacket": 50.00, "socks": 10.00}
print(store)
to_euros = lambda data: (data[0], data[1] * 0.82)
store_euros = list(map(to_euros, store.items()))

for item in store_euros:
    print(item)

#

{'shirt': 20.0, 'pants': 25.0, 'jacket': 50.0, 'socks': 10.0}
('shirt', 16.4)
('pants', 20.5)
('jacket', 41.0)
('socks', 8.2)


In [ ]:
song = "RAH RAH AH AH AH ROM MAH RO MAH MAH"

def generate_word_dict(song):
    song_words = song.lower()
    words_list = song_words.split()
    word_dict = {}

    for w in words_list:
        if w in word_dict:
            word_dict[w] += 1
        else:
            word_dict[w] = 1

    return word_dict

print(generate_word_dict(song))


{'rah': 2, 'ah': 3, 'rom': 1, 'mah': 3, 'ro': 1}


In [ ]:
#My property taxes


import datetime
today = datetime.date.today()
print(f"Today's date is: {today}")
taxes = 2148.65
print(f"The annual tax is ${taxes:,.2f}")
monthly_tax = taxes / 12


print(f"The monthly tax is ${monthly_tax:,.2f}")
taxes_due = datetime.date(2026, 7, 1)
#print(f"The taxes due are {taxes_due}")
#taxes_due = taxes_due.replace(year=today.year)
print(f"The taxes due on {taxes_due}")
time = taxes_due - today
print(f"The time remaining is {time}")
per_day = taxes / time.days
print(f"The daily cost is ${per_day:.2f}")

Today's date is: 2025-12-29
The annual tax is $2,148.65
The monthly tax is $179.05
The taxes due on 2026-07-01
The time remaining is 184 days, 0:00:00
The daily cost is $11.68


In [ ]:
#Auto
from os import times_result
import datetime
today = datetime.date.today()
print(f"Today's date is: {today}")
begin_date = datetime.date(2025, 12, 14)
print(f"The start date is {begin_date}")
time = today - begin_date
print(f"Expired time {time}")

first_milage = 51564
second_milage = 51602
driven_miles = second_milage - first_milage
print(f"Miles driven {driven_miles} miles")
rate = 120.39 * .01
print(f"Depreciation amount ${rate:,.2f}")
depreciation_expense = driven_miles * rate
print(f"Depreciation expense ${depreciation_expense:,.2f}")
miles_per_day = driven_miles / time.days
print(f"Miles per day {miles_per_day:,.2f}")
cost_per_month = miles_per_day * 30.42
print(f"Cost per month ${cost_per_month:,.2f}")
income = 3661.76
print(f"Income ${income:,.2f}")
net_income = income - depreciation_expense
print(f"Net income ${net_income:,.2f}")

Today's date is: 2025-12-29
The start date is 2025-12-14
Expired time 15 days, 0:00:00
Miles driven 38 miles
Depreciation amount $1.20
Depreciation expense $45.75
Miles per day 2.53
Cost per month $77.06
Income $3,661.76
Net income $3,616.01


In [ ]:
names = ["Ana", "John", "Matt", "Katy"]
grades = ["A+", "B","A", "A"]

def get_grade(student, name_list, grade_list):
    i = name_list.index(student)
    grade = grade_list[i]
    return (student, grade)

print(get_grade("Matt", names, grades))

('Matt', 'A')


In [ ]:
mysum = 0
for i in range(5, 11, 2):
    mysum += i
    if mysum == 5:
        break
        mysum += 1
print(mysum)

5


In [ ]:
for i in range(-4, 6, 2):
    print(i)

for i in range(5, 6):
    print(i)

-4
-2
0
2
4
5


In [ ]:
even_numbers = 0

for i in range(10):
    if i % 2 == 0:
        print(i)
        even_numbers += 1

print("Total evens:", even_numbers)


0
2
4
6
8
Total evens: 5


In [ ]:
s = "aaaaabaaaca"
seen = ""


for char in s:
  if char not in seen :
     seen = seen + char
print(len(seen))



3


In [ ]:
import datetime

today = datetime.date.today()
print(f"Today's date is: {today}")

Today's date is: 2025-12-26


In [ ]:
from collections import defaultdict

d = defaultdict(list)

d["strawberry"].append(1)
d["apple"].append(2)
d["banana"].append(3)

print(d)


defaultdict(<class 'list'>, {'strawberry': [1], 'apple': [2], 'banana': [3]})


In [ ]:
#My current position
begin = 16896.61
credit1 = 360.77
credit2 = 1478.98
begin2 = 13248.19
balance1 = begin2 - (credit1 + credit2)
print(f"1.This is the new balance ${balance1:,.2f}")
ss = 2204
balance2 = balance1 + ss
print(f"2.Balance after social security ${balance2:,.2f}")
loss = balance2 - begin
print(f"3.Current spending ${loss:,.2f}")
pension = 1457.76
loss1 = loss + pension
print(f"4.This is the spending after pension ${loss1:,.2f}")
january = loss1 + ss
print(f"5.This is the balance at the beginning of January ${january:,.2f}")
jan_expense = 0.00
loss_in_jan = january - jan_expense
#print(f"6.This is the loss in January ${loss_in_jan:,.2f}")





1.This is the new balance $11,408.44
2.Balance after social security $13,612.44
3.Spending $-3,284.17
4.This is the spending after pension $-1,826.41
5.This is the balance at the beginning of January $377.59


In [ ]:
import functools
letters = ["H", "E", "L", "L", "O"]
word = functools.reduce(lambda x, y,:x + y,letters)
print(word)


factorial = [5, 4, 3, 2, 1]
result = functools.reduce(lambda x, y: x * y,factorial)
print(result)


HELLO
120


In [ ]:
from collections import defaultdict

d = defaultdict(list)

d["apple"].append("red")
d["apple"].append("green")
d["banana"].append("yellow")
d["banana"].append("green")


print(d)

defaultdict(<class 'list'>, {'apple': ['red', 'green'], 'banana': ['yellow', 'green']})


In [ ]:
class Question:
    def __init__(self, prompt, answer):
        self.prompt = prompt
        self.answer = answer


question_prompts = ["What color are apples?\n(a) Red/Green\n(b) Purple\n(c) Orange\n\n",
 "What color are bananas?\n(a) Teal\n(b) Magenta\n(c) Yellow\n\n",
 "What color are strawberries?\n(a) Yellow\n(b) Red\n(c) Blue\n\n"]

questions = [Question(question_prompts[0], "a"),
             Question(question_prompts[1], "c"),
             Question(question_prompts[2], "b"),]

def run_test(questions):
    score = 0
    for question in questions:
        answer = input(question.prompt)
        if answer == question.answer:
            score += 1
    print("You got " + str(score) + "/" + str(len(questions)) + " correct")

run_test(questions)

What color are apples?
(a) Red/Green
(b) Purple
(c) Orange

a
What color are bananas?
(a) Teal
(b) Magenta
(c) Yellow

c
What color are strawberries?
(a) Yellow
(b) Red
(c) Blue

b
You got 3/3 correct


In [ ]:
import random

lowest_number = 26
highest_number = 100
answer = random.randint(lowest_number, highest_number)
guesses = 0

print("Python Number Guessing Game")
print(f"Select a number between {lowest_number} and {highest_number}")

while True:
    guess = input("Enter your guess" )

    if guess.lower() == "q":
        print("Game exited.")
        break

    if guess.isdigit():
        guess = int(guess)
        guesses += 1

        if guess < lowest_number or guess > highest_number:
            print("That number is out of range")
        elif guess < answer:
            print("Too low! Try again!")
        elif guess > answer:
            print("Too high! Try again!")
        else:
            print(f"CORRECT! The answer was {answer}")
            print(f"Number of guesses: {guesses}")
            break
    else:
        print("Invalid guess. Please enter a number.")



Python Number Guessing Game
Select a number between 26 and 100
Enter your guess14
That number is out of range
Enter your guess102
That number is out of range
Enter your guess98
Too high! Try again!
Enter your guess28
Too low! Try again!
Enter your guessq
Game exited.


In [ ]:
squares = []
for i in range(1, 6):

    squares.append(i * i)
print(squares)

[1, 4, 9, 16, 25]


In [ ]:
students = [100, 90, 80, 70, 60, 50, 40, 30, 0]
#passed__students = list(filter(lambda x: x >= 60, students))
#passed__students = [i for i in students if i >= 60]
passed__students = [i  if i >= 60 else "FAILED" for i in students]
print(passed__students)



[100, 90, 80, 70, 60, 'FAILED', 'FAILED', 'FAILED', 'FAILED']


In [ ]:
cities_in_F = {"New York" : 32, "Boston" : 75, "Los Angeles" : 100, "Chicago" : 50}
cities_in_C = {key : round((value-32)*(5/9)) for (key, value) in cities_in_F.items()}
print(cities_in_C)

{'New York': 0, 'Boston': 24, 'Los Angeles': 38, 'Chicago': 10}


In [ ]:
def add(*args):
    sum = 0
    for number in args:
        sum += number
    return sum

print("The total is ", add(1, 2, 31, 89, 102, 7))

The total is  232


In [ ]:
def hello(**kwargs):
    print("Hello, my name is Gregory Lewis.", end=" ")
    #print("Hello, my name is Gregory Lewis.")
    for key, value in kwargs.items():
        print(value, end=" ")

hello()


Hello, my name is Gregory Lewis. 

In [ ]:
#important

beginning_balance = 13248.19
credit_card_1 = 462.45
credit_card_2 = 1478.98
total_credit_card_debt = credit_card_1 + credit_card_2
whats_left_over = beginning_balance - total_credit_card_debt
print(f"This is the amount left after credit cards are paid--> ${whats_left_over:,.2f}")
next_SS = 2204.00
next_amount = whats_left_over + next_SS
print(f"Balance after social security on the 24th is ${next_amount:,.2f}")
the_first_balance = 16896.61

loss = next_amount - the_first_balance
print(f"The loss is ${loss:,.2f}")
upcoming_pension = 1457.76
upcoming_amount = upcoming_pension + loss
print(f"The upcoming amount with this pension is ${upcoming_amount:,.2f}")
January_balance = 2204 + upcoming_amount
print(f"The balance at the end of January is ${January_balance:,.2f}")


This is the amount left after credit cards are paid--> $11,306.76
Balance after social security on the 24th is $13,510.76
The loss is $-3,385.85
The upcoming amount with this pension is $-1,928.09
The balance at the end of January is $275.91


In [ ]:
# Beginning balance-number 1
beginning_balance = 11306.76

# Additions
social_security = 2204.00
pension = 1457.76
# Deductions (corrected)
transfer_to_wife = 1000.00
credit_card_1 = 1148.42
credit_card_2 = 1500.00

# Calculations
balance_after_tincome = beginning_balance + social_security + pension

total_deductions = transfer_to_wife + credit_card_1 + credit_card_2

ending_balance = balance_after_tincome - total_deductions

percent_debt = (total_deductions / balance_after_tincome) * 100
percent_change = ((ending_balance - beginning_balance) / beginning_balance) * 100

# Output
print(f"Beginning Balance: ${beginning_balance:,.2f}")
print(f"Balance After Social Security: ${balance_after_tincome:,.2f}")
print(f"Total Deductions: ${total_deductions:,.2f}")
print(f"Ending Balance: ${ending_balance:,.2f}")
print(f"Debt as % of Balance: {percent_debt:.2f}%")
print(f"Percent Change from Beginning: {percent_change:.2f}%")


Beginning Balance: $11,306.76
Balance After Social Security: $14,968.52
Total Deductions: $3,648.42
Ending Balance: $11,320.10
Debt as % of Balance: 24.37%
Percent Change from Beginning: 0.12%


In [ ]:

from datetime import date

transactions = [
    {"amount": 11.34, "date": date(2025, 6, 4)},
    {"amount": 44.54, "date": date(2025, 6, 10)},
    {"amount": 58.78, "date": date(2025, 6, 19)},
    {"amount": 23.28, "date": date(2025, 8, 8)},
    {"amount": 23.16, "date": date(2025, 9, 6)},
    {"amount": 3.99,  "date": date(2025, 9, 6)},
    {"amount": 77.75, "date": date(2025, 10, 7)},
    {"amount": 69.49, "date": date(2025, 10, 21)},
    {"amount": 72.63, "date": date(2025, 10, 31)},
    {"amount": 76.55, "date": date(2025, 11, 6)},
    {"amount": 33.91, "date": date(2025, 11, 12)},
    {"amount": 57.21, "date": date(2025, 11, 16)},
    {"amount": 40.04, "date": date(2025, 12, 18)},
]

# Calculations
grocery = sum(t["amount"] for t in transactions)
income = 3661.76
cashflow = income - grocery

transaction_count = len(transactions)
average_amount = grocery / transaction_count

# Output
print(f"Grocery amount: ${grocery:.2f}")
print(f"Cashflow: ${cashflow:.2f}")
print(f"Total: ${grocery:.2f}")
print(f"Transactions: {transaction_count}")
print(f"Average: ${average_amount:.2f}")



Grocery amount: $592.67
Cashflow: $3069.09
Total: $592.67
Transactions: 13
Average: $45.59


In [ ]:
import random

def roll_dice(num):
    return random.randint(1, num)

dice_roll = roll_dice(20)
my_number = int(input("Enter your guess (1–20): "))

if my_number == dice_roll:
    print("You won!")
else:
    print("You lost!")

print("The computer picked:", dice_roll)


Enter your guess (1–20): 11
You lost!
The computer picked: 17


In [ ]:
from datetime import date

# -----------------------------
# LOTTERY INPUT
# -----------------------------

total_lottery_spent = float(input("Total lottery spending ($): "))
start_date_input = input("Start date (YYYY-MM-DD): ")

# Optional comparison value is the previous amount spent on lottery tickets:
comparison_amount = float(input("Comparison amount ($), or 0 to skip: ") or 0)
amount = total_lottery_spent - comparison_amount
print(f"Additional amount of spending ${amount:.2f}")
small_winnings = float(input("Total lottery winnings ($): "))
print(f"You have small winnings amount of ${small_winnings:.2f}")
net_cost = total_lottery_spent - small_winnings
print(f"Net lottery cost: ${net_cost:.2f}")


# -----------------------------
# DATE CALCULATION
# -----------------------------

start_year, start_month, start_day = map(int, start_date_input.split("-")) # Changed '/' to '-'
start_date = date(start_year, start_month, start_day)
today = date.today()

days_elapsed = (today - start_date).days
print(f"Days passed: {days_elapsed:.2f} ")
cost_per_day = net_cost / days_elapsed
print(f"Net cost per day ${cost_per_day:.2f}")



# -----------------------------
# CALCULATIONS
# -----------------------------
gross_income = (3710.76 * 11) + 3661.76
print(f"Gross income is ${gross_income:,.2f}")
daily_cost = total_lottery_spent / days_elapsed
annual_cost = daily_cost * 365
monthly_cost = annual_cost / 12
annual_percent = annual_cost / gross_income * 100
print(f"Annual percent is {annual_percent:,.2f}")

# Handle division by zero if comparison_amount is 0
if comparison_amount != 0:
    percent_of_comparison = (total_lottery_spent - comparison_amount) / comparison_amount * 100
else:
    percent_of_comparison = None # Set to None or another suitable value if comparison is not meaningful

# -----------------------------
# OUTPUT
# -----------------------------

print("\n==============================")
print("        LOTTERY SUMMARY")
print("==============================")

print(f"Total Spent: ${total_lottery_spent:,.2f}")
print(f"Days Elapsed: {days_elapsed}")
print(f"Gross cost Per Day: ${daily_cost:.2f}")


print("\nAnnualized View:")
print(f"Annual Cost:  ${annual_cost:,.2f}")
print(f"Monthly Avg:  ${monthly_cost:,.2f}")

if percent_of_comparison is not None:
  #print(f"\nLottery increased by ${comparison_amount:,.2f}: {percent_of_comparison:.2f}%")
  print(f"\nLottery spending increased by {percent_of_comparison:.2f}%")

Total lottery spending ($): 917
Start date (YYYY-MM-DD): 2024-11-25
Comparison amount ($), or 0 to skip: 617
Additional amount of spending $300.00
Total lottery winnings ($): 80.80
You have small winnings amount of $80.80
Net lottery cost: $836.20
Days passed: 428.00 
Net cost per day $1.95
Gross income is $44,480.12
Annual percent is 1.76

        LOTTERY SUMMARY
Total Spent: $917.00
Days Elapsed: 428
Gross cost Per Day: $2.14

Annualized View:
Annual Cost:  $782.02
Monthly Avg:  $65.17

Lottery spending increased by 48.62%


In [ ]:
from datetime import date, datetime

# Get grocery amount-number 3
grocery = float(input("How much was this grocery bill? "))

# Get date as a string
day_input = input("What day did you make the purchase? (mm/dd/yyyy): ")

# Convert string to date object
day = datetime.strptime(day_input, "%m/%d/%Y").date()

# Get today's actual date
today = date.today()

# Calculate difference in days
days_difference = (today - day).days

# Avoid division by zero
if days_difference == 0:
    print("Cannot divide by zero days.")
else:
    result = grocery / days_difference
    print(f"Grocery amount divided by days difference: {result:.2f}")
daily_income = 120.39
print(f"Daily Income: ${daily_income-result:.2f}")

How much was this grocery bill? 40.04
What day did you make the purchase? (mm/dd/yyyy): 12/18/2025
Grocery amount divided by days difference: 40.04
Daily Income: $80.35


In [ ]:
# =========================================================
# CHECKING BALANCE FLOW
# =========================================================

# -----------------------------
# BEGINNING BALANCE
# -----------------------------

beginning_balance = 16896.61
# Current checking balance at start of period

# -----------------------------
# TRANSFER & DEBT
# -----------------------------

transfer_to_wife = 0
# Balance after transfer to wife

credit_card_1 = 462.45
# Amount owed to first credit card

credit_card_2 = 1478.98
# Second credit card balance

total_credit_card_debt = credit_card_1 + credit_card_2

# -----------------------------
# DEBT AS PERCENT OF CHECKING
# -----------------------------

#debt_percent_of_checking = (total_credit_card_debt / beginning_balance) * 100
# Explains the 23.84% figure in spreadsheet
before_ss_income = 13248.19 - total_credit_card_debt
print(f"Income after credit cards are paid ${before_ss_income:,.2f}")

#print(f"Income after social security ${before_ss_income:,.2f}")
ending_balance = before_ss_income + 2204.00
print(f"Balance after social security ${ending_balance:,.2f}")
current = ending_balance - 16896.61
print(f"Loss ${current:,.2f}")

# -----------------------------
# BALANCE AFTER DEBT & TRANSFER
# -----------------------------
#balance_after_debt_and_transfer = non_ss_income - total_credit_card_debt
#print(f"Balance after debt and transfer: ${balance_after_debt_and_transfer:,.2f}")
#balance_after_debt_and_transfer = 10869.21
# Checking balance after paying credit cards and transfer to wife

# -----------------------------
# INCOME ADJUSTMENT
# -----------------------------


# Balance before adding Social Security

social_security = 2204.00
# Monthly Social Security deposit

#balance_after_ss = non_ss_income + social_security
# Spreadsheet shows $16,052.19

# -----------------------------
# PERCENT CHANGE FROM BEGINNING
# -----------------------------

#percent_down_from_beginning = (
    #(balance_after_ss - beginning_balance) / balance_after_ss
#) * 100
# Explains the -5.00% note

# -----------------------------
# NET DIFFERENCE
# -----------------------------

# -----------------------------
# OUTPUT
# -----------------------------

print("\n==============================")
print(" CHECKING BALANCE EXPLANATION")
print("==============================")

print(f"Beginning Checking Balance:        ${beginning_balance:,.2f}")

print("\nTransfers & Debt:")
print(f"  Transfer to Wife:                ${transfer_to_wife:,.2f}")
print(f"  Credit Card #1:                  ${credit_card_1:,.2f}")
print(f"  Credit Card #2:                  ${credit_card_2:,.2f}")
print(f"  Total Credit Card Debt:          ${total_credit_card_debt:,.2f}")
#print(f"  Debt % of Checking:              {debt_percent_of_checking:.2f}%")

print("\nIncome Adjustment:")
#print(f"  Balance Before SS:               ${non_ss_income:,.2f}")
print(f"  Social Security Added:            ${social_security:,.2f}")




Income after credit cards are paid $11,306.76
Balance after social security $13,510.76
Loss $-3,385.85

 CHECKING BALANCE EXPLANATION
Beginning Checking Balance:        $16,896.61

Transfers & Debt:
  Transfer to Wife:                $0.00
  Credit Card #1:                  $462.45
  Credit Card #2:                  $1,478.98
  Total Credit Card Debt:          $1,941.43

Income Adjustment:
  Social Security Added:            $2,204.00


In [ ]:
from os.path import basename
from abc import ABC, abstractmethod

class Shape(ABC):
  @abstractmethod
  def area(self):
    pass

class Circle(Shape):
  def __init__(self, radius):
    self.radius = radius

  def area(self):
    return 3.14 * self.radius ** 2

class Square(Shape):
  def __init__(self, side):
    self.side = side

  def area(self):
    return self.side ** 2

class Triangle(Shape):
  def __init__(self, base, height):
    self.base = base
    self.height = height

  def area(self):
    return self.base * self.height * 0.5

shapes = [Circle(4), Square(5), Triangle(6, 7)]

for shape in shapes:
  print(shape.area())

50.24
25
21.0


In [ ]:
from datetime import date

# =========================================================
# COSTCO SHOPPING LOG-main
# =========================================================

# Tracking start date (as noted in spreadsheet)
tracking_start_date = date(2025, 12, 17)

# Costco purchases: (date, amount)
costco_purchases = [
    (date(2025, 4, 14), 194.13),
    (date(2025, 4, 27), 176.19),
    (date(2025, 5, 8), 161.64),
    (date(2025, 5, 28), 149.05),
    (date(2025, 6, 9), 162.92),
    (date(2025, 6, 21), 115.87),
    (date(2025, 7, 7), 85.13),
    (date(2025, 7, 16), 149.54),
    (date(2025, 7, 27), 160.21),
    (date(2025, 8, 12), 181.48),
    (date(2025, 8, 23), 247.97),
    (date(2025, 9, 9), 247.55),
    (date(2025, 12, 8), 254.35),
]

# -----------------------------
# CALCULATIONS
# -----------------------------

total_spent = sum(amount for _, amount in costco_purchases)

first_purchase_date = min(d for d, _ in costco_purchases)
last_purchase_date = max(d for d, _ in costco_purchases)

days_covered = (last_purchase_date - first_purchase_date).days + 1

daily_cost = total_spent / days_covered

monthly_equivalent = daily_cost * 30.42

# -----------------------------
# OUTPUT
# -----------------------------

print("\n==============================")
print("      COSTCO SPENDING")
print("==============================")

print(f"First Purchase:     {first_purchase_date}")
print(f"Last Purchase:      {last_purchase_date}")
print(f"Days Covered:       {days_covered}")

print(f"\nTotal Spent:        ${total_spent:,.2f}")
print(f"Cost Per Day:       ${daily_cost:.2f}")
print(f"Monthly Equivalent: ${monthly_equivalent:.2f}")



      COSTCO SPENDING
First Purchase:     2025-04-14
Last Purchase:      2025-12-08
Days Covered:       239

Total Spent:        $2,286.03
Cost Per Day:       $9.56
Monthly Equivalent: $290.97


In [ ]:
# =========================================================
# EXPENSE BREAKDOWN (WITH PER-DAY VALUES)-main budget
# =========================================================

expenses = [
    {"percent": 3.98, "category": "CONSUMERS E", "amount": 145.68, "per_day": 4.79},
    {"percent": 3.37, "category": "XFINITY", "amount": 123.32, "per_day": 4.05},
    {"percent": 2.77, "category": "VERIZON", "amount": 101.28, "per_day": 3.33},
    {"percent": 11.50, "category": "AUTO INS", "amount": 421.00, "per_day": 13.84},
    {"percent": 0.68, "category": "NETFLIX", "amount": 24.99, "per_day": 0.82},
    {"percent": 0.38, "category": "YOUTUBE", "amount": 13.99, "per_day": 0.46},
    {"percent": 2.18, "category": "ADT", "amount": 79.97, "per_day": 2.63},
    {"percent": 0.09, "category": "APPLE", "amount": 3.17, "per_day": 0.10},
    {"percent": 0.69, "category": "ADT", "amount": 25.29, "per_day": 0.83},
    {"percent": 2.13, "category": "DTE", "amount": 78.13, "per_day": 2.57},
    {"percent": 8.55, "category": "MEIJER", "amount": 312.90, "per_day": 10.29},
    {"percent": 0.05, "category": "APPLE", "amount": 1.99, "per_day": 0.07},
    {"percent": 1.61, "category": "H&R Block", "amount": 0.00, "per_day": 1.94},
    {"percent": 0.11, "category": "GOOGLE", "amount": 3.99, "per_day": 0.13},
    {"percent": 1.16, "category": "GASOLINE", "amount": 42.43, "per_day": 11.76},
    {"percent": 4.49, "category": "SUMMER TAX", "amount": 164.52, "per_day": 5.41},
    {"percent": 4.35, "category": "HOME INS", "amount": 159.25, "per_day": 5.24},
    {"percent": 2.02, "category": "CASH", "amount": 0.00, "per_day": 2.43},
    {"percent": 0.67, "category": "WINTER TAX", "amount": 24.51, "per_day": 0.81},
    {"percent": 0.24, "category": "MICROSOFT", "amount": 8.83, "per_day": 0.29},
    {"percent": 0.03, "category": "APPLE", "amount": 0.99, "per_day": 0.03},
    {"percent": 0.49, "category": "SALINE", "amount": 0.00, "per_day": 0.59},
    {"percent": 10.92, "category": "LOAN", "amount": 0.00, "per_day": 13.15},
    {"percent": 0.82, "category": "HAIRCUT", "amount": 30.00, "per_day": 0.99},
    {"percent": 1.76, "category": "LOTTERY", "amount": 64.38, "per_day": 2.12},
    {"percent": 0.33, "category": "CHECKBOOK", "amount": 12.00, "per_day": 0.39},
    {"percent": 0.59, "category": "SODA", "amount": 0.00, "per_day": 0.71},
    {"percent": 1.34, "category": "WATER BILL", "amount": 49.09, "per_day": 1.61},
    {"percent": 0.00, "category": "APPLE", "amount": 0.00, "per_day": 0.00},
    {"percent": 7.72, "category": "COSTCO", "amount": 0.00, "per_day": 9.29},
    {"percent": 0.68, "category": "WATER INS", "amount": 24.95, "per_day": 0.82},
    {"percent": 0.00, "category": "NEW TIRES", "amount": 0.00, "per_day": 0.00},
    {"percent": 4.45, "category": "INTEREST", "amount": 0.00, "per_day": 5.36},
    {"percent": 0.49, "category": "Stamps", "amount": 18.00, "per_day": 0.59},
    {"percent": 17.08, "category": "MICHIGAN TAXES", "amount": 0.00, "per_day": 20.56},
]

# -----------------------------
# TOTALS
# -----------------------------

total_amount = sum(item["amount"] for item in expenses)
total_per_day = sum(item["per_day"] for item in expenses)
percent = (total_per_day / 120.39)
print(f"your daily percent is {percent:.2f}")

#
print(f"Total Spent: ${total_amount:,.2f}")
print(f"Total Per Day: ${total_per_day:.2f}")

# Optional: print detailed breakdown
print("\nCategory Breakdown:")
for item in expenses:
    print(f"{item['category']:15} ${item['amount']:8.2f} / Day: ${item['per_day']:6.2f} ({item['percent']}%)")


your daily percent is 1.06
Total Spent: $1,934.65
Total Per Day: $128.00

Category Breakdown:
CONSUMERS E     $  145.68 / Day: $  4.79 (3.98%)
XFINITY         $  123.32 / Day: $  4.05 (3.37%)
VERIZON         $  101.28 / Day: $  3.33 (2.77%)
AUTO INS        $  421.00 / Day: $ 13.84 (11.5%)
NETFLIX         $   24.99 / Day: $  0.82 (0.68%)
YOUTUBE         $   13.99 / Day: $  0.46 (0.38%)
ADT             $   79.97 / Day: $  2.63 (2.18%)
APPLE           $    3.17 / Day: $  0.10 (0.09%)
ADT             $   25.29 / Day: $  0.83 (0.69%)
DTE             $   78.13 / Day: $  2.57 (2.13%)
MEIJER          $  312.90 / Day: $ 10.29 (8.55%)
APPLE           $    1.99 / Day: $  0.07 (0.05%)
H&R Block       $    0.00 / Day: $  1.94 (1.61%)
GOOGLE          $    3.99 / Day: $  0.13 (0.11%)
GASOLINE        $   42.43 / Day: $ 11.76 (1.16%)
SUMMER TAX      $  164.52 / Day: $  5.41 (4.49%)
HOME INS        $  159.25 / Day: $  5.24 (4.35%)
CASH            $    0.00 / Day: $  2.43 (2.02%)
WINTER TAX      $   24.5

In [ ]:
utensils = {"fork", "spoon", "knife", "plate", "bowl"}
dishes = {"bowl", "plate", "cup", "knife"}
print(utensils.intersection(dishes))

dishes.add("napkin")
print(dishes)

#dinner_table = utensils.union(dishes)
#print(dinner_table)
print(dishes.difference(utensils))
print(utensils.difference(dishes))



{'plate', 'bowl', 'knife'}
{'plate', 'napkin', 'bowl', 'knife', 'cup'}
{'napkin', 'cup'}
{'spoon', 'fork'}


In [ ]:
# Vehicle log
from datetime import datetime

auto_log = {
    "vehicle": "Auto",
    "current_date": "2025-12-29",
    "previous_date": "2025-12-14",
    "current_odometer": 51603,
    "previous_odometer": 51564,
}

# Calculate miles driven
miles_driven = auto_log["current_odometer"] - auto_log["previous_odometer"]

# Calculate days between logs


date_format = "%Y-%m-%d"
current_date = datetime.strptime(auto_log["current_date"], date_format)
previous_date = datetime.strptime(auto_log["previous_date"], date_format)
days_between = (current_date - previous_date).days
depreciation_expense = miles_driven / days_between
print(f"Miles Driven: {miles_driven}")
print(f"Days Between: {days_between}")
# Calculate average miles per day
avg_miles_per_day = miles_driven / days_between

#print(f"Miles Driven: {miles_driven}")
#print(f"Days Between: {days_between}")
print(f"Average Miles/Day: {avg_miles_per_day:.2f}")


Miles Driven: 39
Days Between: 15
Average Miles/Day: 2.60


In [ ]:
class Shape:
  def __init__(self, color, is_filled):
    self.color = color
    self.is_filled = is_filled


class Circle(Shape): # Renamed from Circles to match object instantiation
  def __init__(self, color, is_filled, radius):
    super().__init__(color, is_filled)

    self.radius = radius

class Square(Shape):
  def __init__(self, color, is_filled, width): # Added __init__ method
    super().__init__(color, is_filled)
    self.width = width


class Triangle(Shape):
  def __init__(self, color, is_filled, width, height):
    super().__init__(color, is_filled)
    self.width = width
    self.height = height

circle = Circle(color="red", is_filled=True, radius=5)
print(circle.color)
print(circle.is_filled)
print(circle.radius)


red
True
5


In [ ]:
class Animal:
 alive = True

class Dog(Animal):
  def bark(self):
    return "The dog is saying WOOF!"

class Cat(Animal):
  def meow(self):
    return "The cat is saying MEOW!"


class Car:
  def horn(self):
    return "The car is HONKING"


animals = [Dog(), Cat(), Car()]

for animal in animals:
  if isinstance(animal, Dog):
    print(animal.bark())
  elif isinstance(animal, Cat):
    print(animal.meow())
  elif isinstance(animal, Car):
    print(animal.horn())


The dog is saying WOOF!
The cat is saying MEOW!
The car is HONKING


In [ ]:
from typing import List

def avg(grades: List[int]) -> float:
    assert grades, "No grades data"
    return sum(grades) / len(grades)

grades: List[int] = [96, 82, 83, 74, 95, 96, 87, 78, 91, 89]
print(avg(grades))


87.1


In [ ]:

def main():
    x = get_int()
    print(f"You entered the number {x}")

def get_int():
    while True:
        try:
            return int(input("What's x? "))
        except ValueError:
          print("x is not a number")
        else:
          break




main()


What's x? bat
x is not an integer
What's x? 8
You entered the number 8


In [ ]:
from datetime import datetime

# Haircut log with previous date and amount
previous_date_str = "2025-11-25"
amount = 30.00

# Use today's date dynamically
current_date = datetime.today()   # <- updates automatically every day
previous_date = datetime.strptime(previous_date_str, "%Y-%m-%d")
days_between = (current_date - previous_date).days

per_day = amount / days_between

print(f"Days Since Last Haircut: {days_between}")
print(f"Per-Day Cost: ${per_day:.2f}")


Days Since Last Haircut: 33
Per-Day Cost: $0.91


In [ ]:
import random

number = random.randint(1, 26)
print(number)


7


In [ ]:

import random
coin = random.choice(["heads","tails"])
print(coin)

heads


In [ ]:

def main():
    x = get_int("What's x ")
    print(f"x is {x}")


def get_int(prompt):
        while True:
            try:
                return int(input(prompt))
            except ValueError:
                pass

main()

What's x 26
x is 26


In [ ]:

m = int(input("How many times do you want the cat to meow "))
print(f"You asked the cat to meow {m} times")


for _ in range(m):
    print("meow")

How many times do you want the cat to meow 5
You asked the cat to meow 5 times
meow
meow
meow
meow
meow


In [ ]:
#Net income

expenses = [
    145.68, 123.32, 101.28, 24.99, 25.29, 159.25,
    401.57, 165.47, 141.74, 8.39, 200.69, 400.12,
    45.69, 3.17, 1.99, 13.99, 37.98, 178.37,
    24.51, 145.68, .99
]

MONTHLY_INCOME = 3661.76

total_expenses = sum(expenses)
total_income = MONTHLY_INCOME + 0
net = total_income - total_expenses

print(f"Expenses: ${total_expenses:,.2f}")
print(f"Income:   ${total_income:,.2f}")
print(f"Net:      ${net:,.2f}")





Expenses: $2,350.16
Income:   $3,661.76
Net:      $1,311.60


In [ ]:
x = 4*4
g = 3

print(g*g)
print(x/g)
guess = (g + x / g) / 2
print(guess)

9
5.333333333333333
4.166666666666666


div=5//3
print(div)


In [ ]:
div=5//3
print(div)

1


In [ ]:
pi = 3.14
radius = 2.2
area = pi * (radius**2)
radius = radius+1
print(area)
print(radius)
print((area))
print((radius))
print((pi))

15.197600000000003
3.2
15.197600000000003
3.2
3.14


In [ ]:
#Grocery

income = 3661.76
grocery_spending = 426.78

percent = (grocery_spending / income) * 100

print(f"Percent of income spent on grocery: {percent:.2f}%")


Percent of income spent on grocery: 11.66%


In [ ]:
def find_grades(grades, students):

    Lnew = []
    for element in students:
        grade = grades[element]
        Lnew.append(grade)
    return Lnew

d = {"Ana" : "B", "Matt" : "C", "John" : "B", "Katy" : "A"}
d ["Grace"] = "C"
print(find_grades (d,["Matt", "Katy"]))
print("\n")
print(d)
k = d.keys()
print("\n")
print(k)

['C', 'A']


{'Ana': 'B', 'Matt': 'C', 'John': 'B', 'Katy': 'A', 'Grace': 'C'}


dict_keys(['Ana', 'Matt', 'John', 'Katy', 'Grace'])


In [ ]:
def is_pal(x):
    # Convert string to list and reverse
    temp = list(x)
    temp.reverse()

    print("Reversed:", "".join(temp), "Original:", x)  # optional debug

    return temp == list(x)

# Test
print(is_pal("abcba"))  # True
print(is_pal("hello"))  # False




Reversed: abcba Original: abcba
True
Reversed: olleh Original: hello
False


In [ ]:
main()
n = 25
pow(n,2)
print(pow(n,2))

def main():
    name = input("What's your name? ")
    hello(name)

def hello(name):
    print("hello", name)



What's your name? greg
hello greg
625


In [ ]:
def square(x):
    return x ** 2

def cube(x):
    return x ** 3

def fourth(x):
    return x ** 4

def fifth(x):
    return x ** 5

def sixth(x):
    return x ** 6

def seventh(x):
    return x ** 7

def eighth(x):
    return x ** 8

def ninth(x):
    return x ** 9


def main():
    x = int(input("What's x? "))
    print("x squared is", square(x))
    print("x cubed is", cube(x))
    print("x to the 4th power is", fourth(x))
    print("x to the 5th power is", fifth(x))
    print("x to the 6th power is", sixth(x))
    print("x to the 7th power is", seventh(x))
    print("x to the 8th power is", eighth(x))
    print("x to the 9th power is", ninth(x))

main()



What's x? 3
x squared is 9
x cubed is 27
x to the 4th power is 81
x to the 5th power is 243
x to the 6th power is 729
x to the 7th power is 2187
x to the 8th power is 6561
x to the 9th power is 19683


In [ ]:
def is_pal(x):
    return x == x[::-1]

# Test
print(is_pal("abcba"))  # True
print(is_pal("hello"))  # False

True
False


In [ ]:
def make_prod(a):
    def g(b):
        return a*b
    return g
doubler = make_prod(21)

val = doubler(39)
#val = make_prod(2) (3)
print(val)

819


In [ ]:
pi = 3.14
radius = 2.2
area = pi * (radius**2)
radius = radius+1
print(area)
print(radius)
print(id(area))
print(id(radius))

var = type(5*4)
print(var)

15.197600000000003
3.2
138265707835248
138265707829456
<class 'int'>


In [ ]:
a = "me"
z = "you"
b = "myself"
c = a + b
d = a + " " + b
silly = a * 3
print(silly)
print(c)
print(d)
6.3

mememe
memyself
me myself


In [ ]:
b = ":"
c = ")"
d = b + c
print(d)
s1 = b + 2*c
f = "a"
g = " b"
h ="3"
s2 = (f + g) *int (h)
print(s2)

:)
a ba ba b


In [ ]:
f = "a"
g = "b"
h = 3

#s2 = (f + g + " ") * h
#print(s2.strip())
s2 = " ".join(["ab"] * 3)
print(s2)



ab ab ab


In [ ]:
x = int(input("what's x "))
y = int(input("what's y "))

if x < y:
    print("x is less than y")
elif x > y:
    print("x is greater than y")
else:
    print("x is equal to y")

what's x 10
what's y 10
x is equal to y


In [ ]:
x = int(input("what's x "))

if x % 2 == 0:
    print("Even")
else:
    print("Odd")

what's x 21
Odd


In [ ]:
from turtle import *
turtles = [25]
print(turtles)

[25]


In [ ]:


command = ""
started = False

while True:
    command = input("> ").lower()
    if command == "start":
        if started:
            print("Car is already started!")
        else:
            started = True
            print("Car started…")

    elif command == "stop":
        if not started:
            print("Car is already stopped")
        else:

            started = False   # <-- FIXED (was 'stopped = False')
            print("Car stopped")

    elif command == "help":
        print("""
start - to start the car
stop - to stop the car
quit - to exit
        """)

    elif command == "quit":
        break

    else:
        print("Sorry, I don't understand that")

> start
Car started…
> stop
Car stopped
> stop
Car is already stopped
> quit


In [ ]:
age = int(input("Enter your age: "))
has_ticket = True
price = 10.00
price1 = 7.00


if age >= 65:
    print("You are a senior citizen. No ticket required.")

elif age >= 18:
  print("You are an adult. You need a ticket.")
  print(f"The ticket price for an adult is ${price:.2f}")
  print(f"You can buy a ticket for ${price:.2f}")
else:
    print("You are a minor. You need a ticket.")
    print(f"The ticket price for a miinor is ${price1:.2f}")
    print(f"You can buy a ticket for ${price1:.2f}")


Enter your age: 24
You are an adult. You need a ticket.
The ticket price for an adult is $10.00
You can buy a ticket for $10.00


In [ ]:

import random
class Dice:
  def roll(self):
    first = random.randint(1, 6)
    second = random.randint(1, 6)
    return first, second

dice = Dice()
print(dice.roll())

(2, 1)


In [ ]:
for x in range(4):
  for y in range(3):
    print(f"({x}, {y})")

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)


# New Section

In [ ]:
import datetime
today = datetime.date.today()

print(today)
specific_date = datetime.date(2025, 1, 1)  # Year, Month, Day

print("_____________________________________")
print(specific_date)
specific_date1 = datetime.date(2024, 11, 25)  # Year, Month, Day
print(specific_date1)
print("_____________________________________")
now = (today - specific_date1)
now1 = (today - specific_date)

print(now)
print(now1)

2026-01-06
_____________________________________
2025-01-01
2024-11-25
_____________________________________
407 days, 0:00:00
370 days, 0:00:00


In [ ]:
import random
for i in range(10):
   #print(random.randint(10, 95))
   print(i)


0
1
2
3
4
5
6
7
8
9


In [ ]:
numbers = [2, 2, 4, 6, 3, 4, 6, 1]
uniques = []
for number in numbers:
  if number not in uniques:
    uniques.append(number)
print(uniques)

[2, 4, 6, 3, 1]


In [ ]:
status = 500

match status:
  case 400:
    print("Bad request")
  case 404:
    print("Page not found")
  case 500:
    print("Internal server error")
  case _:
    print("Unknown error")

Internal server error


In [ ]:
b = ":"
c = ")"
s1 = b + 2*c
print(s1)

f = "a"
g = " b"
h = "3"
s2 = (f + g) * int (h)
print(s2)



:))
a ba ba b


In [ ]:
started = False

while True:
    command = input("> ").lower()

    if command == "start":
        if started:
            print("Car already started!")
        else:
            started = True
            print("Car started...")

    elif command == "stop":
        if not started:
            print("Car is already stopped!")
        else:
            started = False
            print("Car stopped...")

    elif command == "help":
        print("""
start - to start the car
stop - to stop the car
quit - to quit
        """)

    elif command == "quit":
        break

    else:
        print("I don't understand that")


> start
Car started...
> stop
Car stopped...
> stop
Car is already stopped!
> start
Car started...
> start
Car already started!
> quit


In [ ]:

highIncome = True
goodCredit = False
student = False

#if not student:

if highIncome or goodCredit:
    print("Eligible")
else:
    print("Not eligible")

successful = True
for number in range(3):
   print("Attempt")
   if successful:
     print("Successful")
     break
else:
    print("Attemped 3 times and failed")





command = ""
while command.lower() != "quit":
    command = input(">Enter a word (type quit to stop)")
    print("ECHO", command)
    if command.lower() == "quit":
        break


Eligible
Attempt
Successful
0, 0
0, 1
1, 0
1, 1
2, 0
2, 1
100
50
25
12
6
3
1
>Enter a word (type quit to stop)wan
ECHO wan
>Enter a word (type quit to stop)gregory
ECHO gregory
>Enter a word (type quit to stop)queen
ECHO queen
>Enter a word (type quit to stop)stop
ECHO stop
>Enter a word (type quit to stop)quit
ECHO quit


In [ ]:
for x in range(3):
    for y in range (2):
        print(f"{x}, {y}")


#number = 100
#while number > 0:
 #  print(number)

  # number //= 2



0, 0
0, 1
1, 0
1, 1
2, 0
2, 1


In [ ]:
name = " "
if not name.strip():
    print("Name is empty")
else: print("Name is not empty")

age = 39

if 18 <= age < 65:
    print("Eligible")
else:
    print("Not Eligible")

Name is empty
Eligible


In [ ]:
word = input()
print(word[len(word)-1])
#print(word)

In [ ]:


numbers = [1, 28, 3, 14, 251, 6, 70, 28, 19]


max = numbers[0]

for number in numbers:
  if number > max:
    max = number
print(f"The largest number is {max:}")

The largest number is 251


In [ ]:
num_pad = ((1, 2, 3),
           (4, 5, 6),
           (7, 8, 9),
           ("*", 0, "#"))

for row in num_pad:
    for num in row:
        print(num, end=" ")
    print()

In [ ]:
numbers = [1, 28, 23, 141, 21, 86, 70, 28, 19]

largest = 0
#largest = numbers[0]

for number in numbers:
  if number > largest:
    largest = number
print(largest)

141


In [ ]:
names = []
for i in range(3):
   name = input("Enter a name: ")


   names.append(name)

for name in sorted(names):
  print(f"hello, {name}")


Enter a name: Pam
Enter a name: Rita
Enter a name: Gregory
hello, Gregory
hello, Pam
hello, Rita


In [ ]:
import random
coin = (random.choice([1, 2, 3, 18, 19, 20, 21, 22,  30]))
print(coin)

import random
number = random.randint(1, 75)
print(number)

import random
cards = ["jack", "queen", "king"]
random.shuffle(cards)
for card in cards:
  print(card)

import statistics
print(statistics.mean([10, 32]))


19
18
queen
jack
king
21


In [ ]:
foods = []
prices = []
total = 0
while True:
  food = input("Enter a food to buy (q to quit): ")
  if food.lower() == "q":
    break
  else:
    price = float(input(f"Enter the price of {food}: "))
    foods.append(food)
    prices.append(price)
print("---- YOUR CART ----")
for food in foods:
  print(food)
for price in prices:
  total += price
print(f"Total: ${total}")
cash = 165
cash_left = cash - total
print(f"Cash left over ${cash_left:.2f}")

Enter a food to buy (q to quit): HAMBURGER
Enter the price of HAMBURGER: 8.99
Enter a food to buy (q to quit): FISH
Enter the price of FISH: 10.99
Enter a food to buy (q to quit): STEAK
Enter the price of STEAK: 14.99
Enter a food to buy (q to quit): Q
---- YOUR CART ----
HAMBURGER
FISH
STEAK
Total: $34.97
Cash left over $130.03


In [ ]:
#Hourly rate
Income = (1457.76 + 2204)
print(f"Monthly income ${Income:,.2f}")
annual_income = Income * 12
print(f"Annual income is  ${annual_income:00,.2f}")

print(f"Weekly income is ${annual_income / 52:.2f}")
print(f"Hourly rate is ${annual_income / 52 / 40:.2f}")

daily_income = annual_income / 365
print(f"Per day ${daily_income:.2f}")


Monthly income $3,661.76
Annual income is  $43,941.12
Weekly income is $845.02
Hourly rate is $21.13
Per day $120.39


In [ ]:
def greet_user():
    print("Hi there!")
    print("Welcome aboard")


print("Start")
greet_user()
print("Finish")

Start
Hi there!
Welcome aboard
Finish


In [ ]:
numbers = [3, 6, 2, 8, 4, 10]
max = numbers[0]
for number in numbers:
  if number > max:
    max = number
print(max)

In [ ]:
numbers = [3, 6, 2, 8, 7, 9, 4, 10]

for num in numbers:
  if num % 2 == 0:
    print(num)


6
2
8
4
10


In [ ]:
coordiantes = (1, 2, 3)
print(coordiantes[0])
coordiantes = [(1, 2), (3, 4), (5, 6)]
for coordinate in coordiantes:
  print(coordinate)


In [ ]:
def main():
    x = int(input("What's x? "))
    print("x squared is", square(x))

def square(n):
    return n * n

def test_square():
  if square(2) != 4:
    print("2 squared was not 4")
  if square(3) != 9:
    print("3 squared was not 9")
    print("test failed")


if __name__ == "__main__":
  test_square()
  main()


What's x? 3
x squared is 9


In [ ]:
question = input("Choose a verb: ")
print( f"I can {question:} better than you! ")
print((question+"  " )* 3)





Choose a verb: run
I can run better than you! 
run  run  run  


In [ ]:
x = int(input("What x to find the cube root of? "))
g = int(input("What guess to start with? "))
print(f"Current estimate cubed  = ", g**3)
next_g = (g - (g**3-x) / (3 * g**2))

#print(f"Next guess to try = ", next_g)
print(f"Next guess to try = {next_g:.2f

                             }")

What x to find the cube root of? 7
What guess to start with? 9
Current estimate cubed  =  729
Next guess to try = 6.03


In [ ]:
num = 3000
fraction = 1/3
print(f"{num*fraction:.2f} is {fraction*100:.2f}% of num")

1000.00 is 33.33% of num


In [ ]:
name = "gregory Lewis!"
print(name.upper())
print(name.lower())
print(name.title())
print(name.strip())

GREGORY LEWIS!
gregory lewis!
Gregory Lewis!
gregory Lewis!


In [ ]:
words = ["Python", "fun"]
print(" ".join(words))



In [ ]:
def emoji_converter(message):


    words = message.split(" ")
    emojis = {
        ":)": "😊",
        ":(": "😒"
    }
    output = ""
    for word in words:
        output += emojis.get(word, word) + " "
    return output
    print(output)

message = input(">")
print(emoji_converter(message))




>way
way 


In [ ]:
questions = ("How many elements are in the periodic table?: ",
             "Which animal lays the largest eggs?: (Capitalize your answer) ",
             "What is the most abundant gas in the atmosphere?: (Capitalize your answer) ",
             "How many bones are in the human body?: ",
             "Which planet in the solar system is the hottest?: (Capitalize your answer) ")
answers = (
    "118",
    "Blue Whale",
    "Nitrogen",
    "206",
    "Venus"
)
guesses = []
score = 0
question_num = 0

for question in questions:
    guess = input(question)
    guesses.append(guess)
    if guess == answers[question_num]:
        score += 1

        print("Correct")
    else:
        print("Incorrect")
    question_num += 1
    score = int(score)
print("You got " + str(score) + "/" + str(len(questions)) + " correct")

In [ ]:

import random

x = random.randint(1, 100)
print(x)

myList = ["Gregory", "Linda", "Rita", "Rachel", "Pamela"]
z = random.choice(myList)
print(z)

cards = ["J", "Q", "K", "Ace", 2, 3, 4, 5, 6, 7, 8, 9, 10]
random.shuffle(cards)
print(cards)

In [ ]:
foods = []
prices = []
total = 0
while True:
  food = input("Enter a food to buy (q to quit): ")
  if food.lower() == "q":
    break
  else:
    price = float(input(f"Enter the price of {food}: "))
    foods.append(food)
    prices.append(price)
print("---- YOUR CART ----")
for food in foods:
  print(food)
for price in prices:
  total += price
print(f"Total: ${total}")
ss = 2204
cash_left_from_ss = ss - total
print(f"Cash left from Social Security ${cash_left_from_ss:.2f}")

Enter a food to buy (q to quit): ham
Enter the price of ham: 9.99
Enter a food to buy (q to quit): q
---- YOUR CART ----
ham
Total: $9.99
Cash left from Social Security $2194.01


In [ ]:
class Car:
    def __init__(self, make, model, year, color):
        self.make = make
        self.model = model
        self.year = year
        self.color = color

    def drive(self):
        return("This car is driving")

    def stop(self):
        return("This car is stopped")

car_1 = Car("Chevy", "Corvette", "2021", "blue")
car_2 = Car("Ford", "Mustang", "2022", "red")

print(car_2.make)
print(car_2.model)
print(car_2.year)
print(car_2.color)

print(car_2.drive())
print(car_2.stop())



Ford
Mustang
2022
red
This car is driving
This car is stopped


In [ ]:
class Person:
    def __init__(self, name):
        self.name = name

    def talk(self):
        print(f"Hi, I am {self.name} and I need a job real bad.")

greg = Person("Gregory")
greg.talk()

In [ ]:


monthConversion =  {"Jan":"January",
 "Feb":"February",
 "Mar":"March",
 "Apr":"April",
 "May":"May",
 "Jun":"June",
 "Jul":"July",
 "Aug":"August",
 "Sep":"September",
 "Oct":"October",
 "Nov":"November",
 "Dec":"December"}
#print(monthConversion["Nov"])
#print(monthConversion.get("Nov", "Not a valid key"))

for month in monthConversion:
    print(month)


In [ ]:
def raise_to_power(base_num, pow_num):
    result = 1
    for index in range(pow_num):
        result = result * base_num
    return result

print(raise_to_power(2, 2))

In [ ]:
checking = float(input("Enter your checking balance: "))
print(f"Your checking balance is ${checking:.2f}")
savings = float(input("Enter your savings balance: "))
print(f"Your savings balance is ${savings:,.2f}")
credit = float(input("Enter your credit balance: "))
print(f"Your credit balance is ${credit:.2f}")
pension = float(input("Enter your pension check: "))
print(f"Pension--> ${pension:.2f}")
deposits = float(input("Enter your deposit amount: "))
print(f"Deposit--> ${deposits:.2f}")
new_savings = savings + deposits
print(f"Savings--> ${new_savings:00,.2f}")

pension_bal = pension - credit
print(f"Pension balance after credit card payment ${pension_bal:,.2f}")
total = pension_bal - deposits
print(f"Pension balance after savings deposit ${total:.2f}")
#allowance= total / 30
#print(f"Daily allowance--> ${allowance:.2f} dollars per day until next pay period")

In [ ]:
Income = (1441.69 + 2153)
print(f"Monthly income ${Income:,.2f}")
annual_income = Income * 12
print(f"Annual income is  ${annual_income:00,.2f}")

print(f"Weekly income is ${annual_income / 52:.2f}")
print(f"Hourly rate is ${annual_income / 52 / 40:.2f}")

daily_income = annual_income / 365
print(f"Per day ${daily_income:.2f}")


In [ ]:

secret_word = "apple"
guess = ""
guess_count = 0
guess_limit = 3

out_of_guesses = False

while guess != secret_word and not out_of_guesses:
      if guess_count < guess_limit:
          guess = input("Enter guess: ")
          guess_count += 1


      else:
          out_of_guesses = True

if out_of_guesses:
    print("Out of Guesses, YOU LOSE!")
else:
    print("Good guess, You win!")
#This code worked on this tryout...finally
#On the other code it kept going to win status even though the word was wrong!
#all in the same column before(if and else)did not work...



Enter guess: orange
Enter guess: lewis
Enter guess: apple
Good guess, You win!


In [ ]:
secret_num = 9

num = ""
num_count = 0
num_limit = 3
out_of_guesses = False

while num != secret_num and not out_of_guesses:
      if num_count < num_limit:
        num = int(input("What number is the secret_num? (three guesses)"))
        num_count += 1


      else:
          out_of_guesses = True

if out_of_guesses:
    print("Out of guesses, YOU LOSE!")
else:
    print("You win!")






What number is the secret_num? (three guesses)78
What number is the secret_num? (three guesses)54
What number is the secret_num? (three guesses)13
Out of guesses, YOU LOSE!


In [ ]:

secret_number = 9
number = ""
number_count = 0
number_limit = 3
out_of_numbers = False

while number != secret_number and not out_of_numbers:

    if number_count < number_limit:
       number = int(input("Enter guess: "))
       number_count += 1


    else:
        out_of_numbers = True

if  out_of_numbers:
        print("Your out of Numbers, YOU LOSE!")
else:
        print("You win! You guessed the number:")
#This code worked on this tryout...finally
#Not working number 9 secret number is matching but no win executed.

Enter guess: 45
Enter guess: 69
Enter guess: 21
Your out of Numbers, YOU LOSE!


In [ ]:
def multiply(*numbers):
    total = 1
    for num in numbers:
        total = total * num
    return total
multiply(3, 4,)

In [ ]:
def save_user(**user):
    print(user)
save_user(id=1, name="John", age=22)

In [ ]:
number_grid = [[1, 2, 3], [4, 5, 6],[7, 8, 9], [0]]
#print(number_grid[2][1])

#for row in number_grid:
 # print(row)

for row in number_grid:
  for col in row:
     print(col)


In [ ]:
guess = ""
guesses = []

lucky_numbers = (4, 8, 15, 16, 23, 42, 65)
while guess not in lucky_numbers:
  try:
    guess = int(input("Enter guess: "))
    print(guess)
    guesses.append(guess)
  except KeyboardInterrupt:
    print("\nGame interrupted.")
    break

print(guesses)

Enter guess: 54
54
Enter guess: 27
27
Enter guess: 8
8
[54, 27, 8]


In [ ]:
def fizz_buzz(n):
    if n % 3 == 0 and n % 5 == 0:
        return "fizz buzz"
    elif n % 3 == 0:
        return "fizz"
    elif n % 5 == 0:
        return "buzz"
    else:
        return n
fizz_buzz(11)

11

In [ ]:
num1 = float(input("Enter first number: "))
op = input("Enter operator ")
num2 = float(input("Enter second number: "))

if op == "+":
    print("The answer is ", num1 + num2)
elif op == "-":
    print("The answer is ", num1 - num2)
elif op == "*":
    print("The answer is ", num1 * num2)
elif op == "/":
    print("The answer is ", num1 / num2)
else:
    print("Invalid operator")

Enter first number: 5
Enter operator /
Enter second number: 2
The answer is  2.5


In [ ]:
name = "David"
age = 12
print(name, age)

"""
name = "David"
age = 12
print("%s is %s" % (name, age))
"""

"""
name = "David"
age = 12
print("%s is %d" % (name, age))
"""
"""
name = "David"
age = 12
print("{0} is {1}" .format(name, age))
"""


name = "David"
age = 12
print("{0} is {1}" .format(name, age))


David 12
David is 12


In [ ]:



def say_hi(name, age):
    print("Hello " + name + " how are you today? You just had a birthday you just turned " + age)

say_hi("Gregory ", "69")
say_hi("Linda", "73")
say_hi("Rita ", "65")
say_hi("Terry ", "66")



def cube(num):
    return num * num * num
print(cube(3))



def operators(a, b, c):
    return a * b + c
print("The final result is ", operators(5, 6, 8))




In [ ]:
def translate(phrase):
    translation = ""
    for letter in phrase:
        if letter.lower() in "aeiou":
          if letter.isupper():
                translation = translation + "G"
          else: translation = translation + "g"
        else:
            translation = translation + letter
    return translation
print(translate(input("Enter a phrase: ")))


Enter a phrase: gregory
grgggry


In [ ]:

try:

    number = int(input("Enter a number: "))
    print(number)

except ValueError:

    print("Invalid input")



In [ ]:
a = [135, 247, 359]
b = iter(a)
print(next(b))
print(next(b))
print(next(b))
c = iter(a)
for i in range(len(a)):
    print(next(c))


In [ ]:
list = [5, 6, 7, 8]
print(list)
tuple = (1, 2, 3, 4)
print(tuple)
tuple == list

print(type(tuple))
print(list)
print(type(list))
print(tuple[0])
print(list[1])

[5, 6, 7, 8]
(1, 2, 3, 4)
<class 'tuple'>
[5, 6, 7, 8]
<class 'list'>
1
6


In [ ]:
!pip install scapy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 21.9 MB/s eta 0:00:00


In [ ]:
def show_balance():
    print(f"Your balance is ${balance:.2f}")

def deposit():
    amount = float(input("Enter an amount to be deposited "))
    if amount < 0:
      print("That's not a valid amount")
      return 0

    else:
      return amount

def withdraw():
     amount = float(input("Enter an amount to be withdrawn: "))
     if amount > balance:
      print("Insufficient funds")
     elif amount < 0:
      print("Amount must be greater than 0")
      return 0
     else:
        return amount


balance = 0
is_running = True

while is_running:
    print("Banking Program")
    print("1. Show Balance")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Exit")

    choice = input("Enter your choice (1 - 4): ")

    if choice == "1":
          show_balance()
    elif  choice == "2":
         balance += deposit()
    elif  choice == "3":
          #withdraw()
          balance -= withdraw()
    elif  choice == "4":
          is_running = False
    else:
        print("That is not a valid choice")

print("Thank you for using my banking program")


In [ ]:
beginningBal = 204.88
currentBal = 474.95
endingBal = (currentBal - beginningBal) / beginningBal
newBal = 474.95 - 300
print("Your new balance is ", newBal)
print(f"Balance was up {endingBal:.2f} before you paid $300 on your BoA card")
#print("Ending balance now at $" + str(beginningBal))
print("You had $", (currentBal), "before your payment...$")

print("You now have $" + str(newBal) + " dollars")


Your new balance is  174.95
Balance was up 1.32 before you paid $300 on your BoA card
You had $ 474.95 before your payment...$
You now have $174.95 dollars


In [ ]:
monthlyExpenses = {"Verizon":143.96, "Comcast":137.48, "DTE":64.57,
                   "Microsoft":10.59, "WaterBill":48.37, "ADTSecurity":102.73,
                "AutoIns":405.68, "HomeIns":142.50, "ConsumersEnergy":102.99,
                   "Malware":335.25, "Netflix":22.99, "Youtube":13.99, "Apple":4.17}



total = int(sum(monthlyExpenses.values()))
Social = 2153
print("Social Security $" + str(Social))

print(f"Your operating expenses are ${total:.2f}")
Pension = 1441.69
print("Pension $", Pension)
cash_balance = Pension - 900 - 300 - 50
print(f"Cash Balance ${cash_balance:.2f} from pension after paying credit cards")
print()
print(f"Cash Balance ${cash_balance:.2f} from pension")

mal = 44.47 + 57.23 + 127.72 + 58.14 + 47.69
print()
print("Total cost of Malware bytes security $", mal)
net_ss = (Social-1500-30-42.46-12.01-10.32-38.46-48.63-36.18-35.13-10.32)
print()
print(f"Net cash leftover from SS ${net_ss:.2f}")


In [ ]:
smallest = None
print("The starting number is", smallest)

for the_num in [9, 41, 12, 3, 19, 74, 15, 80]:
    if smallest is None or the_num < smallest:
        smallest = the_num
    print(smallest, the_num)

print("The smallest number in the list is", smallest)



The starting number is None
9 9
9 41
9 12
3 3
3 19
3 74
3 15
3 80
The smallest number in the list is 3


In [ ]:
largest_so_far = 0
print("The starting number is ", largest_so_far)
for the_num in [9, 41, 12, 3, 19, 74, 15, 80]:


  if the_num > largest_so_far:
    largest_so_far = the_num
  print(largest_so_far, the_num)

print("The highest number in the list is ", largest_so_far)




The starting number is  0
9 9
41 41
41 12
41 3
41 19
74 74
74 15
80 80
The highest number in the list is  80


In [ ]:
class Student:

    def __init__(self, name, major, gpa, is_on_probation):
        self.name = name
        self.major = major
        self.gpa = gpa
        self.is_on_probation = is_on_probation

    def on_honor_roll(self):
        if self.gpa >= 3.5:
            print("You are on the honor roll")
            return True

        else:
            print("You are not on the honor roll")
            return False

#on_honor_roll(student3):
#from Student import Student
student1 = Student("Jim", "Business", 3.1, False)
student2 = Student("Pam", "Art", 2.5, True)
student3 = Student("Gregory", "Computer Science", 3.5, False)

print(student3.gpa)



3.5


In [ ]:


class Student:
    def __init__(self, name, major, gpa, is_on_probation):
        self.name = name
        self.major = major
        self.gpa = gpa
        self.is_on_probation = is_on_probation

# No import needed here
student1 = Student("Jim", "Business", 3.1, False)
student2 = Student("Pam", "Art", 2.5, True)
student3 = Student("Gregory", "Computer Science", 3.5, False)

print(student3.name)   # Output: Gregory
print(student3.major)  # Output: Computer Science
print(student3.gpa)    # Output: 3.5
print(student3.is_on_probation)  # Output: False




Gregory
Computer Science
3.5
False


In [ ]:


# Define Chef
class Chef:
    def make_chicken(self):
        print("The chef makes a chicken")
    def make_salad(self):
        print("The chef makes a salad")
    def make_special_dish(self):
        print("The chef makes bbq ribs")

# Define ChineseChef, inheriting from Chef
class ChineseChef(Chef):
    def make_fried_rice(self):
        print("The chef makes fried rice")
    def make_special_dish(self):
        print("The chef makes orange chicken")



In [ ]:
#I finally got this one to work...
newMovie = []
movies = input("What movie do you want?  ")
newMovie.append(movies)
print(newMovie)



#for i in newMovie:
#    print(i)

What movie do you want?  New Jack
['New Jack']


In [ ]:
a = "the "
b = "three "
c = "musketeers."
print(a + str(b) + c)

the three musketeers.


In [ ]:
message = "Hi SpaceX"
for char in message:
  print(char)
  print(message)


H
Hi SpaceX
i
Hi SpaceX
 
Hi SpaceX
S
Hi SpaceX
p
Hi SpaceX
a
Hi SpaceX
c
Hi SpaceX
e
Hi SpaceX
X
Hi SpaceX


In [ ]:
#stuff = list(input("Enter something: "))
#stuff = ("".join(stuff))
#print(stuff)
#name = input("What is your name? ")
#print("Hello " + name)


names = ["Gregory", "Linda", "Rachel", "Wanda", "Pam", "Rita"]
i = 0
while (i < len(names)):
  print(names[i])
  i = i + 1

names.insert(0, "Marissa")
print(names)

Gregory
Linda
Rachel
Wanda
Pam
Rita
['Marissa', 'Gregory', 'Linda', 'Rachel', 'Wanda', 'Pam', 'Rita']


In [ ]:
interest = 155.40
print("This is the amount of interest paid on the Syn credit card $", interest )


In [ ]:
myExpenses = {"Verizon":143.92, "Comcast":137.48, "DTE":64.57, "Microsoft":10.59, "WaterBill":48.37, "ADTSecurity":74.72,
                "AutoIns":410.81, "HomeIns":142.50, "ConsumersEnergy":102.99,"Malware":239.99,
                "Netflix":22.99, "Youtube":13.99, "Apple":4.17}
total = float(sum(myExpenses.values()))

print(f"${total:,.2f}")
print(f"Your total expenses are ${total:,.2f}")
Social = 2153
pension = 1441.69 - total
leftOver = Social -  total
all = pension + Social
Percent = total / Social
print(f"{Social:,.2f}--->This is your Social Security.")
print(f"${leftOver:.2f}--->This is the amount you have leftover.")
print(f"${pension:.2f}--->This is the amount you have left in your pension.")
print("Your estimated Social Security is ", all)
print(f"{Percent:.2f}--->This is the percentage of your Social Security.")


$1,417.09
Your total expenses are $1,417.09
2,153.00--->This is your Social Security.
$735.91--->This is the amount you have leftover.
$24.60--->This is the amount you have left in your pension.
Your estimated Social Security is  2177.6000000000004
0.66--->This is the percentage of your Social Security.


In [ ]:
Salaries = [789, 200, 300, 456, 587, 659]

totalSalary = sum(Salaries)
print(totalSalary)

2991


In [ ]:


ages = [34, 50, 28, 20, 44, 65, 73, 14, 22, 45, 17, 38]

age_Over = 0
i = 0

total_ages = sum(ages)
print("All the ages added together are " + str(total_ages))

Average = total_ages / len(ages)
print(f"The average age is {Average:.2f}")

while i < len(ages):
    if ages[i] > 30:
        age_Over += 1
    i += 1

print("Total ages over 30 are: " + str(age_Over))



All the ages added together are 450
The average age is 37.50
Total ages over 30 are: 7


In [ ]:
Income = (1441.69 + 2153)
print(Income)
print(f"My weekly income is ${Income / 4.5:.2f}")
print(f"My hourly rate is ${Income / 4.5 / 40:.2f}")


3594.69
My weekly income is $798.82
My hourly rate is $19.97


In [ ]:
ages = [34, 50, 28, 20, 44]
numbers_over30 = 0
i = 0
while i < len(ages):
    if ages[i] > 30:
        numbers_over30 = numbers_over30 + 1
    i = i + 1

print("Total over 30: " + str(numbers_over30))

Total over 30: 3


In [ ]:



salaries = [789.36, 200.57, 300.12, 456.39, 587.41, 659.12]
i = 0
while i < len(salaries):
    salaries[i] = salaries[i] * 1.2
    i += 1

# Print each salary formatted to 2 decimals
print("Updated salaries:")
for s in salaries:
    print(f"${s:.2f}")

averageSalary = sum(salaries) / len(salaries)
print(f"My average cost for salaries is: ${averageSalary:.2f}")

totalSalary = sum(salaries)
print(f"My tax added cost for salaries is: ${totalSalary:,.2f}")
#✅ Example Output
#swift
#Copy code
#Updated salaries:
#$947.23
#$240.68
#$360.14
#$547.67
#$704.89
#$790.94
#My average cost for salaries is: $598.59
#My tax added cost for salaries is: $3591.55

Updated salaries:
$947.23
$240.68
$360.14
$547.67
$704.89
$790.94
My average cost for salaries is: $598.59
My tax added cost for salaries is: $3,591.56


In [ ]:
salaries = [3000, 1500, 800, 1200, 1489, 2138.42, 765, 2600]
salaryAccumulator = 0
i = 0
while i < len(salaries):
    salaryAccumulator = salaryAccumulator + salaries[i]
    i = i + 1
print(F"Total salary sum: ${salaryAccumulator:,.2f}")
print("Total count sum: " + str(i))

Total salary sum: $13,492.42
Total count sum: 8


In [ ]:
city1 = {"name":"New York", "population":8550405}
city2 = {"name":"Los Angeles", "population":3971883}
city3 = {"name":"Chicago", "population":2720}
cities = [city1, city2, city3]
counter = 0

for city in cities:
    if(city["population"] > 90000):
        counter = counter + 1

print("Population over 90000: " + str(counter))




Population over 90000: 2


In [ ]:
price1 = 100
price2 = price1
print(price1)
price2 =200
print(price2)


100
200


In [ ]:
num1 = 89
num2 = num1
print(num2)
print(num1)
num2 = 150
print(num2)



In [ ]:
#Practice code
x = (18, 21, 32)
#print(x)
#print(y)
for num in x:
  print(num)

18
21
32


In [ ]:
number = [18, 25, 31, 47, 69]
for item in number:
  print(item)

total = sum(number)
print("The sum of all the numbers are", total)
average = total / len(number)
print("The average of all the numbers is", average)

18
25
31
47
69
The sum of all the numbers are 190
The average of all the numbers is 38.0


In [ ]:

def add():
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    result = num1 + num2
    print("The result is: " + str(result))

def subtract():
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    result = num1 - num2
    print("The result is: " + str(result))

def multiply():
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    result = num1 * num2
    print("The result is: " + str(result))

def divide():
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    if num2 == 0:
        print("Error: Division by zero is not allowed.")
    else:
        result = num1 / num2
        print("The result is: " + str(result))

while True:
    print("\n----Enter the operation----")
    print("1) add")
    print("2) subtract")
    print("3) multiply")
    print("4) divide")
    print("0) Exit")

    operation = int(input("Choose an option (0–4): "))

    if operation == 1:
        add()
    elif operation == 2:
        subtract()
    elif operation == 3:
        multiply()
    elif operation == 4:
        divide()
    elif operation == 0:
        print("Bye =)")
        break
    else:
        print("Invalid choice, please try again.")


----Enter the operation----
1) add
2) subtract
3) multiply
4) divide
0) Exit
Choose an option (0–4): 1
Enter first number: 54
Enter second number: 65
The result is: 119.0

----Enter the operation----
1) add
2) subtract
3) multiply
4) divide
0) Exit
Choose an option (0–4): 2
Enter first number: 456
Enter second number: 126
The result is: 330.0

----Enter the operation----
1) add
2) subtract
3) multiply
4) divide
0) Exit
Choose an option (0–4): 0
Bye =)


In [ ]:
for n in range(1, 120, 33):
  print(n)

1
34
67
100


In [ ]:
for number in range(1, 66, 16):
  print(number)

1
17
33
49
65


In [ ]:
stop = int(input("What number do you want to stop at? "))
for number in range(stop):
  print(f"Your statement has printed {stop} times...")

What number do you want to stop at? 6
Your statement has printed 6 times...
Your statement has printed 6 times...
Your statement has printed 6 times...
Your statement has printed 6 times...
Your statement has printed 6 times...
Your statement has printed 6 times...


In [ ]:
def strangeOccurrence(word):
  print("I saw a "+word+" last night")
strangeOccurrence("UFO")


In [ ]:

"""
import random
def roll_dice(num):
  return random.randint(1, num)
print("The computer picks ", roll_dice(10))
#roll_dice(10)
"""

import random
def roll_dice(num):
  my_number = int(input("Enter your guess: "))
  #return my_number
  if my_number == "roll_dice":
    print("You won!")


  return random.randint(1, num)
print("The computer picks ", roll_dice(2))
roll_dice(10)


Enter your guess: 12
The computer picks  1
Enter your guess: 56


5

In [ ]:
class Question:
    def __init__(self, prompt, answer):
        self.prompt = prompt
        self.answer = answer


question_prompts = ["What color are apples?\n(a) Red/Green\n(b) Purple\n(c) Orange\n\n",
 "What color are bananas?\n(a) Teal\n(b) Magenta\n(c) Yellow\n\n",
 "What color are strawberries?\n(a) Yellow\n(b) Red\n(c) Blue\n\n"]

questions = [Question(question_prompts[0], "a"),
             Question(question_prompts[1], "c"),
             Question(question_prompts[2], "b"),]




def run_test(questions):
    score = 0

    for question in questions:
        answer = input(question.prompt)
        if answer == question.answer:
            score += 1
    print("You got " + str(score) + "/" + str(len(questions)) + " correct")

run_test(questions)

What color are apples?
(a) Red/Green
(b) Purple
(c) Orange

a
What color are bananas?
(a) Teal
(b) Magenta
(c) Yellow

c
What color are strawberries?
(a) Yellow
(b) Red
(c) Blue

b
You got 3/3 correct


In [ ]:

class Question:
    def __init__(self, prompt, answer):
        self.prompt = prompt
        self.answer = answer


question_prompts = ["What is your son's name?\n(a) Anthony\n(b) James\n(c) Harry\n\n",
 "What is your daughter's name?\n(a) Janice\n(b) Annie\n(c) Rachel\n\n",
 "How old are you?\n(a) 64\n(b) 73\n(c) 76\n\n"]

questions = [Question(question_prompts[0], "a"),
             Question(question_prompts[1], "c"),
             Question(question_prompts[2], "b"),]




def run_test(questions):
    score = 0
    for question in questions:
        answer = input(question.prompt)
        if answer == question.answer:
            score += 1
    print("You got " + str(score) + "/" + str(len(questions)) + " correct")

run_test(questions)


What is your son's name?
(a) Anthony
(b) James
(c) Harry

a
What is your daughter's name?
(a) Janice
(b) Annie
(c) Rachel

c
How old are you?
(a) 64
(b) 73
(c) 76

b
You got 3/3 correct


In [ ]:
def add():
  num1 = float(input("Enter first number: "))
  num2 = float(input("Enter second number: "))
  result = num1 + num2
  print("The result is: " + str(result))
#I finally got this one to work...Hooray!!!
def subtract():
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    result = num1 - num2
    print("The result is: " + str(result))

def multiply():
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    result = num1 * num2
    print("The result is: " + str(result))

def divide():
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    result = num1 / num2
    print("The result is: " + str(result))

while True:
  print("----Enter the operation----")
  print("1) add")
  print("2) subtract")
  print("3) multiply")
  print("4) divide")
  print("0) Exit")
  operation = int(input())
  if operation == 1:
    add()
  elif operation == 2:
    subtract()
  elif operation == 3:
    multiply()
  elif operation == 4:
    divide()
  elif operation == 0:
    print("Bye=)")
    break

add()
subtract()
multiply()
divide()

In [ ]:


def help_with_expenses():
    print("How can I help you?")

    # Ask for monthly income
    income = float(input("What is your monthly income? "))
    print(f"${income:.2f}? Okay, let’s see what we can do...")

    # Assume 48% goes to expenses
    expenses = income * 0.60
    leftover = income - expenses

    print(f"Estimated expenses: ${expenses:.2f}")
    print(f"Money left over after expenses: ${leftover:.2f}")

    # Simple advice
    if leftover < 500:
        print("⚠️ You may need to cut costs or look for extra income.")
    else:
        print("✅ Looks like you’re managing okay, keep saving what’s left!")

help_with_expenses()
#💻 Example Run
#bash
#Copy code
#How can I help you?
#What is your monthly income? 1441.69
#$1441.69? Okay, let’s see what we can do...
#Estimated expenses: $576.68
#Money left over after expenses: $865.01
#✅ Looks like you’re managing okay, keep saving what’s left!

How can I help you?
What is your monthly income? 3661.76
$3661.76? Okay, let’s see what we can do...
Estimated expenses: $2197.06
Money left over after expenses: $1464.70
✅ Looks like you’re managing okay, keep saving what’s left!


In [ ]:
#I don't know how to loop through this program...
user = input("What name do you want to use? (Use uppercase)  ")


if(user[0] == "L"):
  print("Name discarded")
else:
 print("Possible name")



In [ ]:
#I don't know how to loop through this program...

#babyNames = None
#babyNames = ["Lucas", "David", "Logan", "Mike"]
#babyNames = user = input("What name do you want to use? (start with uppercase)  ")
user = input("What name do you want to use? (Use uppercase)  ")

if(user[0] == "L"):
#if(babyNames == "L"):
#if(babyNames[0] == "L"):
  #for Names in babyNames:
   # print(babyNames)


  print("Name disarded")
else:
 print("Possible name")
#print(babyNames[0])


In [ ]:
from types import MethodDescriptorType
motorcycles1 = ["Yamaha"]
motorcycles2 = motorcycles1
print(motorcycles1[0])
motorcycles2[0] = "Ducati"
print(motorcycles1[0])
#print(motorcycles2[0])
#print(motorcycles1[0])

Yamaha
Ducati


In [ ]:
ages = [25, 7, 39, 69, 43, 37, 28, 17, 21]
#for age in ages:
 # print(age)
add = sum(ages)
print("All the ages total ", add)
average = add / len(ages)
print(f"The average age is {average:.2f}")


All the ages total  286
The average age is 31.78


In [ ]:
my_Spending2 = {"perch":17.49, "salad":7.91, "bacon":21.65
    ,
               "something4":0.00, "something5":0.00, "something6":0.00,
                "something7":0.00, "something8":0.00, "something9":0.00}

total = float(sum(my_Spending2.values()))
monthly_income = (2153 + 1441.69)

allSpending = total / monthly_income
print(total)  # Output: 60
print("Your total is " + str(total))
print
print("You spend " + str(allSpending) + " of your monthly income")



In [ ]:
def creditCardPayment(daysLate):
  if(daysLate > 7):
    return daysLate * 2
  elif(daysLate > 10):
    return daysLate * 3
  elif(daysLate > 20):
    return daysLate * 4
  elif(daysLate > 30):
    return daysLate * 5
  else:
    return 0

latePayments = int(input("How many days late is your credit card payment? "))
lateFee = creditCardPayment(latePayments)
    #print(f"Your fine is ${fine+10}")
print("You must pay a late fee charge of "+ str(lateFee) +" dollars")
    #print("End of program

How many days late is your credit card payment? 7
You must pay a late fee charge of 0 dollars


In [ ]:
from scapy.all import *
pkt = IP(dst="10.0.0.223")/ICMP()
pkt.show()
send(pkt)


from scapy.all import IP, ICMP, send, sniff

###[ IP ]###
  version   = 4
  ihl       = None
  tos       = 0x0
  len       = None
  id        = 1
  flags     = 
  frag      = 0
  ttl       = 64
  proto     = 1
  chksum    = None
  src       = 172.28.0.12
  dst       = 10.0.0.223
  \options   \
###[ ICMP ]###
     type      = echo-request
     code      = 0
     chksum    = None
     id        = 0x0
     seq       = 0x0
     unused    = b''


Sent 1 packets.


In [ ]:
# prompt: def operate_these_numers():

def operate_these_numbers(n, x):
  print("I am a function")

  print("adding", n + x)
  print("subtracting", n - x)
  print("multiplying", n * x)
  print("dividing", n / x)
  print("modulus", n % x)
  print("exponent", n ** x)
  print("floor division", n // x)

operate_these_numbers(3, 3)

print("End of program")

I am a function
adding 6
subtracting 0
multiplying 9
dividing 1.0
modulus 0
exponent 27
floor division 1
End of program


In [ ]:
def add(x, y):
  z = x + y
  print(z)

add(5, 65)

print("End of program")




In [ ]:
print("Enter your name: ")
name = input()
print("Your name is: ")
print(name)




In [ ]:
cars = ["Chrysler 300", "Pacifica", "Mustang", "Ram 1600"]
print(cars[0])
print(cars[1])
print(cars[2])
print(cars[3])



Chrysler 300
Pacifica
Mustang
Ram 1600


In [ ]:
def add():
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    result = num1 + num2
    print("The result is: " + str(result))

def subtract():
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))
    result = num1 - num2
    print("The result is: " + str(result))

while True:
    print("----Enter the operation----")
    print("1) add")
    print("2) subtract")
    print("0) Exit")
    operation = int(input("Your choice: "))

    if operation == 1:
        add()
    elif operation == 2:
        subtract()
    elif operation == 0:
        print("Bye=)")
        break
    else:
        print("Invalid choice, try again.")
#✅ This way:

#The program only runs inside the loop.

#You don’t get the extra add() and subtract() calls at the end.

#I also added an "Invalid choice" message for wrong inputs.

#Do you want me to also show you how to reduce repeated code (so you don’t have to write num1 = float(input(...)) in every function)?













----Enter the operation----
1) add
2) subtract
0) Exit
Your choice: 63
Invalid choice, try again.
----Enter the operation----
1) add
2) subtract
0) Exit
Your choice: 2
Enter first number: 100
Enter second number: 50
The result is: 50.0
----Enter the operation----
1) add
2) subtract
0) Exit
Your choice: 0
Bye=)


In [ ]:


def add():
  num1 = float(input("Enter first number: "))
  num2 = float(input("Enter second number: "))
  result = num1 + num2
  print("The result is: " + str(result))
  while(True):
    print("----Enter the operation----")
    print("1. Add")
    print("0. Exit")

    operation = int(input())
    if(operation == 1):
      add()
    elif(operation == 0):
        print("Bye=)")
        break


add()

In [ ]:
singers = ["5th harmony", "Mariah Carey,", "Micheal Jackson", "Jessie J."]
singer1 = singers[0]
print(len(singers))
print(singer1)
print(singers[2])
print(singers[len(singers)-1])


4
5th harmony
Micheal Jackson
Jessie J.


In [ ]:
i = int(input("Enter a number: "))
while (i <= 6):
  print(i)
  i = i+1
print("End of program")


Enter a number: 1
1
2
3
4
5
6
End of program


In [ ]:
name = None
while (name != "greg"):
 name = input("Enter a name: ")
print("Welcome", name)

Enter a name: bill
Enter a name: greg
Welcome greg


In [ ]:
while True:
    capital = input("Columbus is the capital of which US state? ")

    if capital.strip().lower() == "ohio":
        print("Congratulations you won the trivia!")
        break
    else:
        print("Try again")

print("End of game")



Columbus is the capital of which US state? Michigan
Try again
Columbus is the capital of which US state? Ohio
Congratulations you won the trivia!
End of game


In [ ]:
message = "location: Provenza"
messageLower =  message.lower()
messageUpper = message.upper()
print(messageLower)
print(messageUpper)
countA = message.count("a")
print(countA)
newMessage = message.replace("x", "a")
print(newMessage)

In [ ]:

Stuff = []
word = input("Enter a word: ")
#print(word[0])
#print(word[len(word)-1])
#print(word[:2])
APPEND = Stuff.append(word)
print(Stuff)

In [ ]:
food = "Pizza"
#print(food.find("z"))
num = food.count("a")
if num > 0:

  print(f"Text contains {num} letters")
else:
  print("Text is not in Pizza... ")

In [ ]:
motorcycles = ["Honda", "Yamaha", "Suzuki"]
print(motorcycles[0])
motorcycles[0] = "Ducati"
print(motorcycles[0])

In [ ]:
"""
aliens = []
aliens.append("E.T.")
aliens.append("Goku")
aliens.append("Marvin")
aliens.append("Gazoo")
print(aliens[3])
"""
aliens = ["E.T", "Goku", "Marvin", "Gazoo"]
print(aliens[1])
aliens.pop(3)
#print(aliens[0])
print(aliens)

In [ ]:
aliens = ["E.T", "Goku", "Marvin", "Gazoo", "Maroon"]
i = 0
while (i < len(aliens)):
  print(aliens[i])
  i = i + 1

In [ ]:
colors = ["Yellow", "Blue", "Red"]
print(len(colors))
print(colors)

In [ ]:
from ast import PyCF_ALLOW_TOP_LEVEL_AWAIT
PyCF_ALLOW_TOP_LEVEL_AWAIT

In [ ]:
secretMessage = ["Planet", "You", "Secret", "Are", "Zombie", "The", "Nuclear", "Alien"]
i = 1
while (i <= len(secretMessage)):
  print(i)
  i = i + 2
print(secretMessage[1:8:2])

1
3
5
7
['You', 'Are', 'The', 'Alien']


In [ ]:
myData = {"name":"gregory", "age":69, "height":5.4}
product = {"name":"iPhone 14", "price":799, "color":"midnight"}
print(myData)
print(type(myData))
print(product)
print(type(product))


In [ ]:
grades = [4.5, 3.0, 5.0]
days = ["Monday", "Tuesday", "Wednesday"]
ages = [40, 12, 29, 55]
print(grades)
print(days)
print(ages)


In [ ]:
computer = {"brand":"Gateway", "processor":"i5"}
character = {"name":"Magician", "attack":20}
country = {"name":"Columbia", "capitalCity":"Bogata"}
print(len(computer))
print(computer["brand"])
print(computer["processor"])
print(character["name"])
print(country["name"])

2
Gateway
i5
Magician
Columbia


In [ ]:
car = {"brand":"Toyota", "color":"Black"}
print(car)
#print(len(car))
#print(car["brand"])
#print(car["color"])
#car["color"] = "Red"
#print(car)
#car["cargoBox"] = "Skybox16"
#car["fender"] = "PocketStyle"
#print(car)
#car.pop("cargoBox")
#print(car)

for key in car:
  print(key)
  print(car[key])

{'brand': 'Toyota', 'color': 'Black'}
brand
Toyota
color
Black


In [ ]:
word = input("What word are you using? ")

for i in range(len(word)):
    if word[i] not in "aeiou":
        # consonant
        print(f"{word[i]} is a consonant")
    else:
        # vowel
        print(f"{word[i]} is a vowel")




#This code is not working correctly...prints out the whole word.
#It's coded correctly in the file named "Vowels"
#Check the "Vowel" file...





What word are you using? apple
a is a vowel
p is a consonant
p is a consonant
l is a consonant
e is a vowel


In [ ]:
movieN = input("Enter the movie's name ")
movieA = input("Enter the movie's name ")
movieG = input("Enter the movie's name ")
print(movieN)
print(movieA)
print(movieG)


allMovies = [movieN, movieA, movieG]
print(allMovies)
#I created this one...

Enter the movie's name newjack
Enter the movie's name lou
Enter the movie's name today
newjack
lou
today
['newjack', 'lou', 'today']


In [ ]:
#It works with this code...
#Program won't stop own it's own...
number = input("Put in a number you like: ")

i = 0

while (i <= int(number)):
       print(i)
       i = i + 1


else:
    print("I'm done")

Put in a number you like: 12
0
1
2
3
4
5
6
7
8
9
10
11
12
I'm done


In [ ]:
teams = int(input("How many teams have seen you ? "))

i = 0

while(i <= teams):
  print(i)
  i = i + 1
else:
  print("I'm finished")


In [ ]:
from pickle import NEWOBJ_EX
from posixpath import lexists
word = None
word = input("What word are you using? ")
#newWord = word.pop("a")

print (f"{word} is the word you typed in")
#print(newWord)

What word are you using? apple
apple is the word you typed in


In [ ]:


def greet():
  return "Hi! I hope you are doing okay"
print(greet(), "Gregory")
print(greet(), "Linda")
print(greet(), "Rachel")
print(greet(), "Rita")
print("Welcome")
print("To my program")
greet()
print("End of program")

In [ ]:
stuff = "Hello\nWorld!"
print(stuff)

print(len(stuff))
#print(stuff)
moreStuff = "Gregory\nLewis"
print(moreStuff)

In [ ]:

age = int(input("Enter your age: "))

if(age >= 65):
  print("You are an older adult")

elif(age >= 45):
  print("You are a middle age adult")

elif(age >= 18):
  print("You are a relative young adult")

elif(age >= 10):
  print("You are not an adult yet")





In [ ]:
message = "Have a Good Day!"
indexO = message.find("o")
indexGood = message.find("Good")
indexDay = message.find("Day")

print(indexO)
print(indexGood)
print(indexDay)
print(message[0:16:])

8
7
12
Have a Good Day!


In [ ]:
#productName_productPrice_productQuantity

product = "Laser-100-20"
indexDash1 = product.find("-")
indexDash2 = product.find("-", indexDash1 + 1)
subStringQuantity = product[indexDash2+1:len(product)]

print(indexDash1)
print(indexDash2)
print(subStringQuantity)

5
9
20


In [ ]:
product = "Laser-100-20"
name, price, quantity = product.split("-")
print("name", name)
print("price", price)
print("quantity", quantity)

name Laser
price 100
quantity 20


In [ ]:
word = input("Enter a word: ")
i = 0
while(i < len(word)):
 print(word[i], end="")
 i = i + 1
print()
print(f"The word {word} is complete...")





Enter a word: Mississippi
Mississippi
The word Mississippi is complete...


In [ ]:
text = "Price: 250"
subString = text[0:6]
print(subString)
subString2 = text[7:10]
print(subString2)

In [ ]:
total = 0
count = 0

while True:
    inp = input("Enter a number (press q to quit): ")
    if inp.lower() == "q":  # allow 'Q' too
        break
    try:
        value = float(inp)
    except ValueError:
        print("Please enter a valid number.")
        continue

    total += value
    count += 1
    average = total / count
    print(f"The running average is {average:.2f}")
#Fixed Code (final average only ✅)
#python
#Copy code
total = 0
count = 0

while True:
    inp = input("Enter a number (press q to quit): ")
    if inp.lower() == "q":
        break
    try:
        value = float(inp)
    except ValueError:
        print("Please enter a valid number.")
        continue

    total += value
    count += 1

if count > 0:
    average = total / count
    print(f"The final average is {average:.2f}")
else:
    print("No numbers were entered.")





Enter a number (press q to quit): 58
The running average is 58.00
Enter a number (press q to quit): 45
The running average is 51.50
Enter a number (press q to quit): 4
The running average is 35.67
Enter a number (press q to quit): 6
The running average is 28.25
Enter a number (press q to quit): q
Enter a number (press q to quit): q
No numbers were entered.


In [ ]:
abc = "With three words"
stuff = abc.split()
print(stuff)
print(len(stuff))
print(stuff[0])



['With', 'three', 'words']
3
With


In [ ]:
productPrice = 150
print(productPrice)
productPrice = 250.5
print(productPrice)


In [ ]:
print("Enter your name: ")
name = input()
print("Your name is: ")
print(name)


In [ ]:
a = 10
b = 15
if (a == 3 and b == 4):
    print (f"a = {a:} and b = {b:}")

elif (a == 9 or b == 2):
    print (f"a = {a:} or b = {b}")
elif (a == 10 and b == 15):
    print (f"a = {a:} and b = {b:}")
else:
    print("no match")


a = 10 and b = 15


In [ ]:
numberList = []  # start with an empty list

while True:
    inp = input("Enter a number (or 'done' to finish): ")

    if inp.lower() == "done":  # check before converting
        break

    try:
        number = int(inp)  # convert to int safely
        numberList.append(number)
        print("Current list:", numberList)

        average = sum(numberList) / len(numberList)
        print("Average:", average)

    except ValueError:
        print("Please enter a valid number or 'done'.")

Enter a number (or 'done' to finish): 13
Current list: [13]
Average: 13.0
Enter a number (or 'done' to finish): 56
Current list: [13, 56]
Average: 34.5
Enter a number (or 'done' to finish): 75
Current list: [13, 56, 75]
Average: 48.0
Enter a number (or 'done' to finish): done


In [ ]:

load = 500
type = "Tractor"
if load < 600 and type == "Tractor":
  print("Correct")

else:
  print("Not Correct")

Correct


In [ ]:
names = ['Ana', 'John', 'Matt', 'Katy']
grade = ['A+', 'B', 'A', 'A']
microquizzes = [8, 10, 9, 7]
psets = [7, 8, 9, 6]

def print_grades(student, name_list, grade_list, quiz_list, pset_list):
  i = name_list.index(student)
  grades = grade_list[i]
  quiz = quiz_list[i]
  pset = pset_list
  return f"Student: {student}, Grade: {grades}, Quiz: {quiz}, Pset: {pset}"

print(print_grades("John", names, grade, microquizzes, psets))

Student: John, Grade: B, Quiz: 10, Pset: [7, 8, 9, 6]


In [ ]:
#jerseyNumber = 19

jerseyNumber = int(input("What is your jersey number "))
if jerseyNumber == 19:
  print("What are you looking at fool? Get back there!")
else:
  print("Okay you are doing alright so far.")


What is your jersey number 21
Okay you are doing alright so far.


In [ ]:
alert = float(input("What is the magnitude of the earthquake? "))
if alert >= 5.2:
  print('Warning! This is a Tsunami alert!!')
else:
  print("No worries yet...Everything apears to be normal.")

What is the magnitude of the earthquake? 4
No worries yet...Everything apears to be normal.


In [ ]:


side = float(input("Enter the length of the square's side: "))
if(side > 0):
   area = side * side
   print("The area of the square is: "+str(area))
else:

  print("Square's side must be greater than zero")


In [ ]:
from typing_extensions import AsyncContextManager
number1 = 17
number2 = 110
bothNumbers = number1 + number2
print(bothNumbers)


In [ ]:
stuff = list()
stuff.append("book")
stuff.append(99)
#print(stuff)
stuff.append("cookies")
print(stuff)
for i in stuff:
  print(i)

['book', 99, 'cookies']
book
99
cookies


In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numbers.append("book")
numbers.append("cookies")
numbers.append("need money")

print(numbers)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'book', 'cookies', 'need money']


In [ ]:
numbers = [3, 41, 12, 9, 74, 15]
print(len(numbers))
print(max(numbers))
print(min(numbers))
print(sum(numbers))
#print(mul(numbers))
print(sorted(numbers))
#print(count(numbers))
print(sum(numbers) / len(numbers))



6
74
3
154
[3, 9, 12, 15, 41, 74]
25.666666666666668


In [ ]:
x = 5
print('Hello')
def printLyrics() :
  print('I live at 21191 Midway...')
  print('I no longer work at Meijer...')
  print('No weekly check coming in')
printLyrics()
x = x + 2
print(x)


Hello
I live at 21191 Midway...
I no longer work at Meijer...
No weekly check coming in
7


In [ ]:
def greetings(language):
  if language == "Spanish":
    print("Hola")
  elif language == "French":
    print("Boujour")
  else:
    print("Hello")

greetings("English")
greetings("Spanish")
greetings("French")

#greetings()

Hello
Hola
Boujour


In [ ]:
def greet(lang):
  if lang == "es":
    print("Hola")
  elif lang == "fr":
    print("Bonjour")
  else:
    print("Hello")
greet("en")
greet("es")
greet("fr")


Hello
Hola
Bonjour


In [ ]:
def myName(Name):
  if Name == "Lewis":
    print("This time my name is Greory Lewis.")
  elif Name == "Watson":
    print("This time my name is Greory Watson.")
  else:
    print("Different last names but the same person...")
myName("Lee")
myName("Lewis")
myName("Watson")




Different last names but the same person...
This time my name is Greory Lewis.
This time my name is Greory Watson.


In [ ]:
def customGreeting(firstName, lastName):
  print("Hello " + firstName + " " + lastName)
customGreeting("Gregory", "Lewis")

customGreeting("Rachel", "Williams")


Hello Gregory Lewis
Hello Rachel Williams


In [ ]:
fruit = "Apple"
index = 0
while index < len(fruit):
  letter = fruit[index]
  print(index, letter)
  index = index + 1






0 A
1 p
2 p
3 l
4 e


In [ ]:
def find_in_L(Ld, k):
    for d in Ld:
        if k == d:
            return True
    return False

d1 = {1:2, 3:4, 5:6}
d2 = {2:4, 4:6}
d3 = {1:1, 3:9, 4:16, 5:25}

print(find_in_L(d1, 1))
print(find_in_L(d2, 1))
print(find_in_L(d3, 1))


True
False
True


In [ ]:
capitals = {"USA" : "Washington D.C.",
            "India" : "New Delhi",
            "China" : "Beijing",
            "Russia" : "Moscow"}

#print(dir(capitals))
print("\n")
print(capitals.get("USA"))
#print(help(capitals))
print("\n")
#print(capitals.get("China"))

if(capitals.get("USA")):
    print("That capital exits")
else:
    print("That capital doesn't exist")
capitals.update({"Germany" : "Berlin"})
print(capitals)


In [ ]:
def mean(*args):
    tot = 0
    for a in args:
        tot += a
    return tot/len(args)

print(mean(1, 62, 13, 54, 5, 96))

38.5


In [ ]:

def char_counts(s):
    (c, v) = (0, 0)
    vowels = "aeiou"
    for char in s:
      if char in vowels:
        v += 1
      else:
        c += 1

    return (v, c)
print(char_counts("abcd"))
print(char_counts("zcght"))
print(char_counts("aeiou"))
print(char_counts("dklox"))


In [ ]:
import time

for seconds in range(10, 0, -1):
    print(seconds)
    time.sleep(1)
    print("Happy New Year")

In [ ]:
class Animal:

    alive = True

    def eat(self):
      print("This animal is eating")

    def sleep(self):
      print("This animal is sleeping")

class Rabbit(Animal):
  def run(self):
    print("This rabbit is running")

class Fish(Animal):
  def swim(self):
    print("This fish is swimming")


class Hawk(Animal):
  def fly(self):
    print("This hawk is flying")

rabbit = Rabbit()
fish = Fish()
hawk = Hawk()

#class Dog(Animal):
 #   def bark(self):
  #    print("This dog is barking")

rabbit.run()
fish.swim()
hawk.fly()
  #dog = Dog()

# print(rabbit.alive)
 # rabbit.eat()
  #rabbit.sleep()


This rabbit is running
This fish is swimming
This hawk is flying


In [ ]:
class Car:
  def turn_on(self):
      print("You start the engine")

  def drive(self):
      print("You drive the car")

  def brake(self):
    print("You step on the brake")

  def turn_off(self):
    print("You turn off the engine")

car = Car()

car.turn_on()
car.drive()


You start the engine
You drive the car


In [ ]:
def apply(criteria, n):

    count = 0
    for i in range(n+1):
         if criteria(i):
            count += 1
    return count

def is_even (x):
    return x%2 == 0
print(apply(is_even, 10))



a = [1, 2, 3]
b = [4, 5, 6]

sum_list = list(map(lambda x, y: x + y, a, b))
print(sum_list)


In [ ]:
class Prey:
    def flee(self):
        print("This animal flees")

class Predator:
    def hunt(self):
        print("This animal is hunting")

class Rabbit(Prey):
    pass

class Hawk(Predator):
    pass

class Fish(Prey, Predator):
    pass

rabbit = Rabbit()
hawk = Hawk()
fish = Fish()




rabbit.flee()
hawk.hunt()
fish.flee()
fish.hunt()


This animal flees
This animal is hunting
This animal flees
This animal is hunting


In [ ]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

squared = list(map(lambda x: x**2, nums))
print(squared)

In [ ]:
class Animal:
    def eat(self):
        print("This animal is eating")

class Rabbit(Animal):

    def eat(self):
      print("This rabbit is eating a carrot")

rabbit = Rabbit()
rabbit.eat()


This rabbit is eating a carrot


In [ ]:
def apply(criteria, n):
    if not callable(criteria):
        raise TypeError("criteria must be a function")
    count = 0
    for i in range(n+1):
        if criteria(i):
            count += 1
    return count

def is_even(x):
    return x % 2 == 0

print(apply(is_even, 10))  # Works

In [ ]:
character_name = "Gregory"
character_age = 70

print(character_name)
print(character_age)
print(f"There once was a man named {character_name}, ")
print(f"He was {character_age} years old. ")
print(f"He really liked the name {character_name}, ")
print(f"but did not like being {character_age} years old. ")
print("\n")

In [ ]:
x = 4*4
g = 4.008333333

print(g*g)
print(x/g)
guess = (g + x / g) / 2
print(guess)

In [ ]:
fruit = 'banana'

index = 0
while index < len(fruit):
  letter = fruit[index]
  print(index, letter)
  index = index + 1

In [ ]:
names = []

for name in range(7):
 names.append(input("What's your name? "))
for name in sorted(names):
    print(name)
    break

In [ ]:
from pickle import BINPERSID


x = "a"
id(x)
x * 2 == "aa"
x != "a"


bin(12)
! python --version

Python 3.12.11


In [ ]:
def hello():
  print("hello")

name = input("What is your name? ")
hello()
print(name)

In [ ]:
def hello(to):
  print("hello", to)

name = input("What is your name? ")
hello(name)



In [ ]:
def hello():

  print("hello", name)
name = input("What is your name? ")
hello()


pip install cowsay


In [ ]:
def main(name):
  hello()

def hello():
  print(f"hello {name}")

name = input("What is your name? ")
main()



In [ ]:
import statistics
print(statistics.mean([10, 32]))

21


In [ ]:
import sys

print("hello, my name is", sys.argv[1])


hello, my name is -f


In [ ]:
import random
coin = random.choice(["heads", "tails"])
print(coin)

heads


In [ ]:
import random
coin = (random.choice([1, 2, 3, 18, 19, 20, 21, 22,  30]))
print(coin)

2


In [ ]:
import random
number = random.randint(1, 75)
print(number)


In [ ]:
import random
cards = ["jack", "queen", "king"]
random.shuffle(cards)
for card in cards:
  print(card)


In [ ]:
from random import choice
coin = choice(["heads", "tails"])
print(coin)

In [ ]:
def cube(number):
  return number * number * number

#print(cube(3))
cube(2)

8

In [ ]:
myInfo =({"name: Greg"}, {"Address:: 21191 Midway"})

for i in myInfo:
  print(myInfo)

In [ ]:
name = input("What's your name? ")
name = name.capitalize()
match name:
  case "Rita":
    print("You live in Detroit Michigan...")
  case "Greg":
    print("You live in Southfield Michigan...")
  case "Gay":
    print("You live in Port Huron Michigan...")
  case "Carey":
    print("You live in Canton Michigan...")
  case "Rachel":
    print("You live in Gross Point Michigan...")
  case _:
    print("This name is not in list:")


In [ ]:
try:
  x = int(input("What's x? "))
  print(f"x is {x}")
except ValueError:
  print("x is not an interger")

In [ ]:
students = ["Marlon", "Antoine", "Neka"]
print(students)

print(students[2])


In [ ]:
students = ["Hermione", "Harry", "Ron"]
for student in students:
    print(student)


In [ ]:
students = ["James  Annie  Monica"]
for i in range(len(students)):
  print(i + 1, students[i])


In [ ]:
students = ["Hermione", "Harry", "Ron"]
for i  in range(len(students)):
    print(i)

In [ ]:
students = ["Hermione", "Harry", "Ron"]
for i in range(len(students)):
    print(students[i])

In [ ]:
i = 3
while i != 0:
  print("meow")
  i = i - 1


meow
meow
meow


In [ ]:
i = 1
while i <= 3:
  print("meow")
  i += 1

meow
meow
meow


In [ ]:
for i in [0, 1, 2]:
  print("meow")


meow
meow
meow


In [ ]:
for i in range(3):
  print("meow")

meow
meow
meow


In [ ]:
for cat in range(4):
  print("meow  ", end="")


meow  meow  meow  meow  

In [ ]:
print("meow\n" * 3, end="")

meow
meow
meow


In [ ]:
print("meow  " * 3)

meow  meow  meow  


In [ ]:
while True:
  n = int(input("What's n? "))
  if n > 0:
      break

for item in range(n):
    print("meow")


What's n? 3
meow
meow
meow


In [ ]:

def main():
    number = get_number()
    meow(number)

def get_number():
    while True:
        n = int(input("What's n? "))
        if n > 0:
            break
    return n

def meow(n):
    for cat in range(n):
      print("meow")

main()


What's n? 3
meow
meow
meow


In [ ]:
def main():

   number = get_number()
   new(number)

def get_number():
    while True:
        n = int(input("What's n? "))
        if n > 0:
            return n

def new(n):
    for _ in range(n):
      print("hurry up!")
main()

What's n? -6
What's n? -7
What's n? -21
What's n? -65
What's n? 4
hurry up!
hurry up!
hurry up!
hurry up!


In [ ]:
def f(expr, old_list, test = lambda x: True):
    new_list = []
    for item in old_list:
        if test(item):
            new_list.append(expr(item))
    return new_list

print(f(lambda e: e**2, range(4)))          # [0, 1, 4, 9, 16, 25]
print(f(lambda e: e**2, range(10), lambda e: e % 2 == 0))  # [0, 4, 16]



[0, 1, 4, 9]
[0, 4, 16, 36, 64]


In [ ]:
print(list.reverse.__doc__)
['append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


Reverse *IN PLACE*.


['append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
def hello(to="World"):
     print("Hello,", to)


hello()
name = input("What's your name? ")
hello(name)

In [ ]:
def hello(to):
     print("hello,", to)


name = input("What's your name? ")
hello(name)


In [ ]:
def main():
    x = int(input("What's x? "))
    print("x squared is", square(x))


def square(n):
    return n * n


main()



In [ ]:
def main():
    x = int(input("What's x? "))
    print("x multiplied by x is", square(x))


def square(n):
    return n * n


main()

x = int(input("What's x? "))
result = (x + x)
print(f"x added to x is {result}")

x = int(input("What's x? "))
result = (x - x)
print(f"x substracted from x is {result}")

x = int(input("What's x? "))
result = (x / x)
print(f"x divided by x is {result}")



In [ ]:
def main():
    x = int(input("What's x? "))
    print("x multiplied by x is", square(x))


def square(number):
    return number * number


main()

x = int(input("What's x? "))
result = (x + x)
print(f"x added to x is {result}")

x = int(input("What's x? "))
result = (x - x)
print(f"x substracted from x is {result}")

x = int(input("What's x? "))
result = (x / x)
print(f"x divided by x is {result}")

In [ ]:
def main():
    x = int(input("What's x? "))
    print("x multiplied by x is", square(x))


def square(n):
    return n * n


main()

number = int(input("What's x? "))
result1 = (number + number)
print(f"{number} added to {number} is {result1}")

number = int(input("What's x? "))
result2 = (number - number)
print(f"{number} substracted from {number} is {result2}")

number = int(input("What's x? "))
result3 = (number / number)
print(f"{number} divided by {number} is {result3}")


What's x? 27
x multiplied by x is 729
What's x? 4
4 added to 4 is 8
What's x? 3
3 substracted from 3 is 0
What's x? 5
5 divided by 5 is 1.0


In [ ]:

2




In [ ]:
while True:
    n = int(input("What number does n represent? "))
    if n > 0:
       break
for i in range(n):
    print("meow")






In [ ]:
L = "gregory lewis"
print(L)


In [ ]:
x = float(input("What's x? "))
y = float(input("What's y? "))
z = (x + y)
print(f"The answer is {z:,.2f} ")

In [ ]:
x = float(input("What's x? "))
y = float(input("What's y? "))
z = round(x + y)
print(f"The answer is {z:,} when the two numbers are added... ")


In [ ]:
x = float(input("What's x? "))
y = float(input("What's y? "))
z = (x + y)
print(f"These two numbers added together is {z} ")

What's x? 6
What's y? 7
These two numbers added together is 13.0 


In [ ]:
x = int(input("What's x? "))
y = int(input("What's y? "))
z = (x + y)
print(f"The answer is {z} ")

In [ ]:
def main():
  x = int(input("What's x? "))
  print("x squared is", square(x))

def square(n):
  return n * n

if __name__ == "__main__":
  main()


What's x? 7
x squared is 49


In [ ]:
password = None
while password != "1214":
  print("What is the password?")
  password = input()

print("Yes the password is " + password + "...you may enter ")

What is the password?
pop
What is the password?
iju
What is the password?
1214
Yes the password is 1214...you may enter 


In [ ]:
name = input("What's your name? ")

print("Raw input:", repr(name))
print("Capitalize:", repr(name.capitalize()))
print("Strip:", repr(name.strip()))
print("Title:", repr(name.title()))


name = name.strip().title()
print(f"Hello, {name}")

What's your name? Gregory
Raw input: 'Gregory'
Capitalize: 'Gregory'
Strip: 'Gregory'
Title: 'Gregory'
Hello, Gregory


In [ ]:
started = False

while True:
    command = input("> ").lower()

    if command == "start":
        if started:
            print("Car already started!")
        else:
            started = True
            print("Car started...")

    elif command == "stop":
        if not started:
            print("Car is already stopped!")
        else:
            started = False
            print("Car stopped...")

    elif command == "help":
        print("""
start - to start the car
stop - to stop the car
quit - to quit
        """)

    elif command == "quit":
        print("Goodbye!")
        break


> start
Car started...
> start
Car already started!
> quit
Goodbye!


ModuleNotFoundError: No module named 'scapy'

In [ ]:
def make_prod(a):
    def g(b):
        return a * b
    return g

val = make_prod(2)(3)
print(val)

doubler = make_prod(2)
val = doubler(3)
print(val)
#Output:
#Copy code
#6
#6

6
6


 repr



In [ ]:

name = input("What is your name? ")
print("hello, ", name, sep='')
print("Hello", name + "...")
print(name)
print("Hello " +   name     + " How are you?")
print('"Hello", "friend..."')
print("Hello, \"friend\"")
print("Hello, friend")


What is your name? greg
hello, greg
Hello greg...
greg
Hello greg How are you?
"Hello", "friend..."
Hello, "friend"
Hello, friend


In [ ]:
myName = "greg lewis"
myName = myName.capitalize()
myName = myName.strip()
myName = myName.title()
print(myName)


Greg Lewis


In [ ]:
try:
  x = int(input("What's x? "))

  print(f"{x} is the number")


except ValueError:
    print("x is not an integer")








What's x? cat
x is not an integer


In [ ]:
from multiprocessing import Process
import os

def worker():
    print(f"Process ID: {os.getpid()}")

if __name__ == "__main__":
    processes = []
    for _ in range(4):
        p = Process(target=worker)
        p.start()
        processes.append(p)

    for p in processes:
        p.join()


Process ID: 16130
Process ID: 16133
Process ID: 16138
Process ID: 16143


In [ ]:
from multiprocessing import Process, Queue

def worker(q):
    q.put("Hello from process")

if __name__ == "__main__":
    q = Queue()
    p = Process(target=worker, args=(q,))
    p.start()
    print(q.get())
    p.join()


Hello from process


In [ ]:
from tkinter import *

window = Tk()                 # create the window first
window.geometry("420x420")    # then configure it

window.mainloop()


TclError: no display name and no $DISPLAY environment variable

In [ ]:
while True:
  try:
      x = int(input("What's is x? "))
  except ValueError:
      print("x is not an integer")
  else:
    break
print(f"x is {x}")

In [ ]:
while True:
  try:
      x = int(input("What's is x? "))
      break
  except ValueError:
      print("X should be an interger,\n" + "but you entered a character.")
      print("Enter a number please...")
print(f"You entered a {x}")

In [ ]:

def main():
    x = get_in()
    print(f"x is {x}")

def get_in():
    while True:
        try:
           x = int(input("What's is x? "))
        except ValueError:
            print("x is not an integer")
        else:
            break
    return x
main()

What's is x? 26
x is 26


In [ ]:
def main():

    x = get_in()
    print(f"x is {x}")

def get_in():
    while True:
        try:
           x = int(input("What's is x? "))
        except ValueError:
            print("x is not an integer")
        else:
            return x
main()

What's is x? 7
x is 7


In [ ]:
def main():

    x = get_in()
    print(f"You have entered the number {x}")

def get_in():
    while True:
        try:
           return int(input("What's is x? "))
        except ValueError:
            print("x is not an integer")

main()

What's is x? 17
You have entered the number 17


In [ ]:
def main():

    x = get_in()
    print(f"x is the number {x}")

def get_in():
    while True:
        try:
           return int(input("What's is x? "))
        except ValueError:
            pass

main()

What's is x? 17
x is the number 17


In [ ]:
def main():

    x = get_in("What's x? ")
    print(f"x is equal to {x}")

def get_in(prompt):
    while True:
        try:
           return int(input(prompt))
        except ValueError:
            pass

main()

What's x? 4
x is equal to 4


In [ ]:
def happy_birthday(name, age):

    print(f"Happy birthday to you! You are {age} years old")
    print(f"Happy birthday, dear {name}!")
    print("Happy birthday to you!")

happy_birthday("Linda", 74)




Happy birthday to you! You are 74 years old
Happy birthday, dear Linda!
Happy birthday to you!


In [ ]:
def main():
  x = int(input("What is x? "))
  if is_even(x):
      print (f"{x} is an even number")
  else:
      print(f"{x} is an odd number")
def is_even(n):
    return n % 2 == 0
main()


What is x? 3
3 is an odd number


In [ ]:
num_pad = ((1, 2, 3),
           (4, 5, 6),
           (7, 8, 9),
           ("*", 0, "#"))

for row in num_pad:
    for column in row:
        print(column, end=" ")
    print()

1 2 3 
4 5 6 
7 8 9 
* 0 # 


In [ ]:
rows = int(input("How many rows?: "))
print()
columns = int(input("How many columns?: "))
print()
symbol = (input("Enter a symbol to use: "))


for i in range(rows):
    for j in range(columns):
        print(symbol, end="")
    print()


How many rows?: 7

How many columns?: 6

Enter a symbol to use: *
******
******
******
******
******
******
******


In [ ]:
def display_invoice(invoice, customer, total):
    print("INVOICE")
    print("-" * 50)

    print(f"Invoice number: {invoice}")
    print(f"Customer name: {customer}")
    print(f"Total amount: ${total:.2f}")
    print()

display_invoice(15, "Lewis", 159.56)
display_invoice(14, "Johnson", 499.56)

INVOICE
--------------------------------------------------
Invoice number: 15
Customer name: Lewis
Total amount: $159.56

INVOICE
--------------------------------------------------
Invoice number: 14
Customer name: Johnson
Total amount: $499.56



In [ ]:


import sys
if len(sys.argv) < 2:
  print("Too few arguments")
elif len(sys.argv) > 2:
      print("Too many arguments")
print("hello, my name is", sys.argv[1])


Too many arguments
hello, my name is -f


SyntaxError: invalid syntax. Perhaps you forgot a comma? (ipython-input-1209157064.py, line 3)

In [ ]:
import random

def spin_slot_machine():
    """Simulates a single spin of a slot machine."""
    reels = ["Cherry", "Bell", "Lemon", "Orange", "Star", "Skull"]
    result = [random.choice(reels), random.choice(reels), random.choice(reels)]
    return result

def check_win(result):
    """Checks if the spin result is a win."""
    if result[0] == result[1] == result[2]:
        print("JACKPOT! Three of a kind!")
        return True
    elif result[0] == result[1] or result[1] == result[2] or result[0] == result[2]:
        print("Two of a kind!")
        return True
    else:
        print("No win this spin.")
        return False

# Main game loop
print("Welcome to the simple slot machine!")
while input("Press Enter to spin (or type 'quit' to exit): ").lower() != 'quit':
    spin_result = spin_slot_machine()
    print("Spinning...")
    print(f"Result: {spin_result}")
    check_win(spin_result)

print("Thanks for playing!")

Welcome to the simple slot machine!
Press Enter to spin (or type 'quit' to exit): 
Spinning...
Result: ['Bell', 'Cherry', 'Lemon']
No win this spin.
Press Enter to spin (or type 'quit' to exit): 
Spinning...
Result: ['Cherry', 'Skull', 'Bell']
No win this spin.
Press Enter to spin (or type 'quit' to exit): 
Spinning...
Result: ['Star', 'Star', 'Lemon']
Two of a kind!
Press Enter to spin (or type 'quit' to exit): 
Spinning...
Result: ['Star', 'Cherry', 'Orange']
No win this spin.
Press Enter to spin (or type 'quit' to exit): 
Spinning...
Result: ['Lemon', 'Bell', 'Cherry']
No win this spin.
Press Enter to spin (or type 'quit' to exit): 
Spinning...
Result: ['Cherry', 'Star', 'Orange']
No win this spin.
Press Enter to spin (or type 'quit' to exit): 
Spinning...
Result: ['Orange', 'Orange', 'Orange']
JACKPOT! Three of a kind!
Press Enter to spin (or type 'quit' to exit): quit
Thanks for playing!


In [ ]:
def is_pal(x):
  temp = x
  temp.reverse
  if temp == x:
    return True
  else:
    return False

# Task
Create a simple dice game where the user guesses the sum of two dice rolls. The game should include a loop to allow multiple rounds.

In [ ]:
import random

def roll_dice():
    """Simulates rolling two dice and returns their sum."""
    die1 = random.randint(1, 6)
    die2 = random.randint(1, 6)
    return die1 + die2

def play_game():
    """Plays a round of the dice guessing game."""
    dice_sum = roll_dice()
    while True:
        try:
            user_guess = int(input("Guess the sum of two dice (2-12): "))
            if 2 <= user_guess <= 12:
                break
            else:
                print("Please enter a number between 2 and 12.")
        except ValueError:
            print("Invalid input. Please enter a number.")

    print(f"The dice rolled a total of {dice_sum}.")

    if user_guess == dice_sum:
        print("Congratulations! You guessed correctly!")
    else:
        print("Sorry, that's incorrect.")

# Game loop
print("Welcome to the Dice Guessing Game!")
while True:
    play_game()
    play_again = input("Play again? (yes/no): ").lower()
    if play_again != 'yes':
        break

print("Thanks for playing!")

Welcome to the Dice Guessing Game!
Guess the sum of two dice (2-12): 6
The dice rolled a total of 9.
Sorry, that's incorrect.
Play again? (yes/no): yes
Guess the sum of two dice (2-12): 9
The dice rolled a total of 8.
Sorry, that's incorrect.
Play again? (yes/no): yes
Guess the sum of two dice (2-12): 8
The dice rolled a total of 8.
Congratulations! You guessed correctly!
Play again? (yes/no): no
Thanks for playing!


In [ ]:
import random

def spin_slot_machine():
    """Simulates a single spin of a slot machine."""
    reels = ["Cherry", "Bell", "Lemon", "Orange", "Star", "Skull"]
    return [random.choice(reels) for _ in range(3)]

def check_win(result, bet):
    """Checks if the spin result is a win and returns the payout."""
    if result[0] == result[1] == result[2]:
        print("🎉 JACKPOT! Three of a kind!")
        return bet * 10   # jackpot = 10x payout
    elif result[0] == result[1] or result[1] == result[2] or result[0] == result[2]:
        print("✨ Two of a kind!")
        return bet * 2    # 2x payout
    else:
        print("💀 No win this spin.")
        return 0

# --- Main game loop ---
credits = 20
print("🎰 Welcome to the slot machine!")
print(f"You start with {credits} credits.")

while credits > 0:
    print(f"\nYou have {credits} credits.")
    bet_input = input("Place your bet (or type 'quit' to cash out): ").lower()
    if bet_input == "quit":
        break

    # validate bet
    if not bet_input.isdigit():
        print("❌ Please enter a valid number.")
        continue
    bet = int(bet_input)

    if bet <= 0:
        print("❌ Bet must be at least 1 credit.")
        continue
    if bet > credits:
        print("❌ You don't have enough credits for that bet.")
        continue

    # spin the reels
    credits -= bet
    print("\nSpinning...")
    spin_result = spin_slot_machine()
    print(f"Result: {spin_result}")

    # check winnings
    winnings = check_win(spin_result, bet)
    credits += winnings
    print(f"💰 You won {winnings} credits!")

print(f"\n🏁 Game over. You leave with {credits} credits.")
print("Thanks for playing! 🎲")
#🔹 Example Run
#sql
#Copy code
#🎰 Welcome to the slot machine!
#You start with 20 credits.

#You have 20 credits.
#Place your bet (or type 'quit' to cash out): 5

#Spinning...
#Result: ['Cherry', 'Cherry', 'Star']
#✨ Two of a kind!
#💰 You won 10 credits!

#You have 25 credits.
#Place your bet (or type 'quit' to cash out): quit

#🏁 Game over. You leave with 25 credits.
#Thanks for playing! 🎲


🎰 Welcome to the slot machine!
You start with 20 credits.

You have 20 credits.
Place your bet (or type 'quit' to cash out): 1

Spinning...
Result: ['Skull', 'Cherry', 'Cherry']
✨ Two of a kind!
💰 You won 2 credits!

You have 21 credits.
Place your bet (or type 'quit' to cash out): 1

Spinning...
Result: ['Lemon', 'Skull', 'Bell']
💀 No win this spin.
💰 You won 0 credits!

You have 20 credits.
Place your bet (or type 'quit' to cash out): 1

Spinning...
Result: ['Star', 'Lemon', 'Cherry']
💀 No win this spin.
💰 You won 0 credits!

You have 19 credits.
Place your bet (or type 'quit' to cash out): 1

Spinning...
Result: ['Lemon', 'Cherry', 'Skull']
💀 No win this spin.
💰 You won 0 credits!

You have 18 credits.
Place your bet (or type 'quit' to cash out): 1

Spinning...
Result: ['Lemon', 'Orange', 'Lemon']
✨ Two of a kind!
💰 You won 2 credits!

You have 19 credits.
Place your bet (or type 'quit' to cash out): 1

Spinning...
Result: ['Lemon', 'Orange', 'Bell']
💀 No win this spin.
💰 You won 0 

In [ ]:
def sum_digits(s):
  total = 0
  for char in s:
    if char in "0123456789":
        val = int(char)
        total += val
  return total

print(sum_digits("9836"))



26


In [ ]:
def sum_digits_except(s):
  total = 0
  for char in s:
      try:
        val = int(char)
        total += val
      except:
        print(f"could't convert character", char)

  return total

print(sum_digits_except("15983"))




26


## Generate dice rolls

### Subtask:
Write code to simulate rolling two dice.


**Reasoning**:
The subtask is to simulate rolling two dice. This involves generating two random numbers and calculating their sum. I will write a code block to perform these steps.



In [ ]:
questions = [
    {"prompt": "What is the capital of France?\n(a) London\n(b) Berlin\n(c) Paris\n\n", "answer": "c"},
    {"prompt": "What is the largest planet in our solar system?\n(a) Earth\n(b) Jupiter\n(c) Mars\n\n", "answer": "b"},
    {"prompt": "What is the chemical symbol for water?\n(a) O2\n(b) H2O\n(c) CO2\n\n", "answer": "b"}
]

correct_answers = 0

for question_data in questions:
    answer = input(question_data["prompt"])
    if answer.lower() == question_data["answer"].lower():
        correct_answers += 1
        print("Correct!")
    else:
        print("Incorrect.")

average = correct_answers / len(questions) * 100
print(f"Your average is {average:.2f} percent")
print(f"You got {correct_answers} out of {len(questions)} questions correct.")



What is the capital of France?
(a) London
(b) Berlin
(c) Paris

b
Incorrect.
What is the largest planet in our solar system?
(a) Earth
(b) Jupiter
(c) Mars

c
Incorrect.
What is the chemical symbol for water?
(a) O2
(b) H2O
(c) CO2

b
Correct!
Your average is 33.33 percent
You got 1 out of 3 questions correct.
